<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ModularPipelines" Version="3.2.8" />
    <PackageVersion Include="Sourcy.DotNet" Version="1.1.1" />
    <PackageVersion Include="TedToolkit.RoslynHelper" Version="2026.6.9" />
  </ItemGroup>
</Project>