// -----------------------------------------------------------------------
// <copyright file="BindingNativeErrorTransportEmitter.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

namespace TedToolkit.CppBindings.Generator.Semantics;

/// <summary>
/// Emits the provider-neutral native diagnostic carrier, copy, set, and clear mechanisms.
/// </summary>
public static class BindingNativeErrorTransportEmitter
{
    /// <summary>
    /// Renders a standalone diagnostic transport header.
    /// </summary>
    /// <param name="clearFunction">The exported diagnostic clear function.</param>
    /// <param name="setterFunction">The diagnostic setter function.</param>
    /// <param name="includeStackTrace">Whether the setter accepts copied native stack text.</param>
    /// <param name="providerPreamble">Optional provider-specific includes or helper declarations.</param>
    /// <returns>The complete generated header.</returns>
    public static string RenderHeader(
        string clearFunction,
        string setterFunction,
        bool includeStackTrace = false,
        string providerPreamble = "")
    {
        Validate(clearFunction, setterFunction);
        ArgumentNullException.ThrowIfNull(providerPreamble);
        var builder = new StringBuilder("// <auto-generated />\n#pragma once\n\n");
        if (!string.IsNullOrWhiteSpace(providerPreamble))
        {
            _ = builder.Append(providerPreamble.Trim()).Append("\n\n");
        }

        AppendCarrier(builder);
        _ = builder.Append("extern \"C\" void ").Append(clearFunction)
            .Append("(NativeError* error) noexcept;\nextern \"C\" void ").Append(setterFunction)
            .Append("(\n    NativeError* error,\n    int kind,\n    const char* typeName,\n")
            .Append("    const char* message");
        if (includeStackTrace)
        {
            _ = builder.Append(",\n    const char* stackTrace");
        }

        return builder.Append(") noexcept;\n").ToString();
    }

    /// <summary>
    /// Renders a standalone diagnostic transport implementation.
    /// </summary>
    /// <param name="headerFileName">The generated transport header file name.</param>
    /// <param name="clearFunction">The exported diagnostic clear function.</param>
    /// <param name="setterFunction">The exported diagnostic setter function.</param>
    /// <param name="copyFunction">The private text-copy helper name.</param>
    /// <param name="includeStackTrace">Whether the setter copies native stack text.</param>
    /// <returns>The complete generated implementation.</returns>
    public static string RenderSource(
        string headerFileName,
        string clearFunction,
        string setterFunction,
        string copyFunction,
        bool includeStackTrace = false)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(headerFileName);
        Validate(clearFunction, setterFunction, copyFunction);
        var builder = new StringBuilder("// <auto-generated />\n#include \"")
            .Append(headerFileName).Append("\"\n\n#include <cstdlib>\n#include <cstring>\n\n");
        AppendDefinitions(builder, clearFunction, setterFunction, copyFunction, includeStackTrace, true);
        return builder.ToString();
    }

    /// <summary>
    /// Renders diagnostic transport support inside one generated native source.
    /// </summary>
    /// <param name="clearFunction">The exported diagnostic clear function.</param>
    /// <param name="setterFunction">The private diagnostic setter function.</param>
    /// <param name="copyFunction">The private text-copy helper name.</param>
    /// <returns>The generated inline transport support.</returns>
    public static string RenderInline(string clearFunction, string setterFunction, string copyFunction)
    {
        Validate(clearFunction, setterFunction, copyFunction);
        var builder = new StringBuilder();
        AppendCarrier(builder);
        AppendDefinitions(builder, clearFunction, setterFunction, copyFunction, false, false);
        return builder.ToString();
    }

    private static void AppendCarrier(StringBuilder builder)
    {
        _ = builder.Append(
            "struct NativeError\n{\n    int Kind;\n    char* TypeName;\n    char* Message;\n"
            + "    char* StackTrace;\n};\n\n");
    }

    private static void AppendDefinitions(
        StringBuilder builder,
        string clearFunction,
        string setterFunction,
        string copyFunction,
        bool includeStackTrace,
        bool exportSetter)
    {
        _ = builder.Append("static char* ").Append(copyFunction)
            .Append("(const char* value) noexcept\n{\n    if (value == nullptr) return nullptr;\n")
            .Append("    const auto length = std::strlen(value) + 1;\n")
            .Append("    auto* copy = static_cast<char*>(std::malloc(length));\n")
            .Append("    if (copy != nullptr) std::memcpy(copy, value, length);\n    return copy;\n}\n\n")
            .Append("extern \"C\" void ").Append(clearFunction)
            .Append("(NativeError* error) noexcept\n{\n    if (error == nullptr) return;\n")
            .Append("    std::free(error->TypeName);\n    std::free(error->Message);\n")
            .Append("    std::free(error->StackTrace);\n    *error = {};\n}\n\n")
            .Append(exportSetter ? "extern \"C\" void " : "static void ").Append(setterFunction)
            .Append("(\n    NativeError* error,\n    int kind,\n    const char* typeName,\n")
            .Append("    const char* message");
        if (includeStackTrace)
        {
            _ = builder.Append(",\n    const char* stackTrace");
        }

        _ = builder.Append(") noexcept\n{\n    if (error == nullptr) return;\n    error->Kind = kind;\n")
            .Append("    error->TypeName = ").Append(copyFunction).Append("(typeName);\n")
            .Append("    error->Message = ").Append(copyFunction).Append("(message);\n")
            .Append("    error->StackTrace = ");
        _ = includeStackTrace
            ? builder.Append(copyFunction).Append("(stackTrace);\n}\n")
            : builder.Append("nullptr;\n}\n");
    }

    private static void Validate(string clearFunction, string setterFunction, string? copyFunction = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(clearFunction);
        ArgumentException.ThrowIfNullOrWhiteSpace(setterFunction);
        if (copyFunction is null)
        {
            return;
        }

        ArgumentException.ThrowIfNullOrWhiteSpace(copyFunction);
    }
}