// -----------------------------------------------------------------------
// <copyright file="BindingFiniteProfileEmitter.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

namespace TedToolkit.CppBindings.Generator.Semantics;

/// <summary>
/// Emits finite profile adapters from composable transport and result semantics.
/// </summary>
public static class BindingFiniteProfileEmitter
{
    /// <summary>
    /// Emits the managed half of one finite profile.
    /// </summary>
    /// <param name="api">The finite-profile API.</param>
    /// <param name="profile">The provider emission profile.</param>
    /// <param name="slots">The resolved native export slots.</param>
    /// <returns>The complete managed source.</returns>
    public static string RenderManaged(
        BindingFiniteProfileApi api,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        ArgumentNullException.ThrowIfNull(api);
        ArgumentNullException.ThrowIfNull(profile);
        ArgumentNullException.ThrowIfNull(slots);
        BindingFiniteProfileValidator.Validate(api, profile, slots);
        return new BindingFiniteProfileManagedComposer(api, profile, slots).Compose().ToCode();
    }

    /// <summary>
    /// Emits the native half of one finite profile.
    /// </summary>
    /// <param name="api">The finite-profile API.</param>
    /// <param name="profile">The provider emission profile.</param>
    /// <returns>The complete native source.</returns>
    public static string RenderNative(BindingFiniteProfileApi api, BindingEmissionProfile profile)
    {
        ArgumentNullException.ThrowIfNull(api);
        ArgumentNullException.ThrowIfNull(profile);
        BindingFiniteProfileValidator.Validate(api, profile);
        var builder = new StringBuilder("// <auto-generated />\n")
            .Append(api.NativePreamble.Trim()).Append("\n\n");
        AppendNativeErrorSupport(builder, profile, api.NativeUnknownExceptionMessage);
        foreach (var owner in api.Owners)
        {
            AppendNativeDestroy(builder, owner);
        }

        foreach (var operation in api.Operations)
        {
            AppendNativeOperation(builder, api, operation);
        }

        foreach (var export in api.AdditionalNativeExports)
        {
            _ = builder.Append("extern \"C\" ").Append(export.ReturnType).Append(' ')
                .Append(export.Name).Append('(').Append(export.Parameters).Append(") noexcept\n{\n")
                .Append(Indent(export.Body, 4)).Append("\n}\n\n");
        }

        return builder.ToString();
    }

    private static void AppendNativeOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingFiniteOperationDefinition operation)
    {
        switch (operation)
        {
            case BindingBufferOwnerOperationDefinition buffer:
                AppendNativeBufferOwnerOperation(builder, api, buffer);
                break;

            case BindingCompositeOperationDefinition composite:
                AppendNativeCompositeOperation(builder, api, composite);
                break;

            case BindingOwnedOperationDefinition owned:
                AppendNativeOwnedOperation(builder, api, owned);
                break;

            case BindingScalarOperationDefinition scalar:
                AppendNativeScalarOperation(builder, api, scalar);
                break;

            case BindingTwoPhaseOperationDefinition twoPhase:
                AppendNativeTwoPhaseOperation(builder, api, twoPhase);
                break;
        }
    }

    private static void AppendNativeBufferOwnerOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingBufferOwnerOperationDefinition operation)
    {
        var owner = Find(api.Owners, operation.OwnerName, static value => value.Name);
        _ = builder.Append("extern \"C\" ").Append(operation.NativeReturnType).Append(' ')
            .Append(operation.NativeExport).Append("(\n    ").Append(owner.NativeName).Append("* result");
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append(",\n    const ").Append(buffer.NativeElementType).Append("* ")
                .Append(ToCamelCase(buffer.Name)).Append(",\n    std::size_t ")
                .Append(ToCamelCase(buffer.Name)).Append("Count");
        }

        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n");
        if (operation.OwnedResultName is not null)
        {
            _ = builder.Append("    return Guard<").Append(operation.NativeReturnType).Append(">(error, ")
                .Append(operation.NativeFailureExpression).Append(", [&]()\n    {\n")
                .Append(Indent(operation.NativeBody, 8)).Append("\n    });\n");
        }
        else
        {
            _ = builder.Append("    Guard<int>(error, 0, [&]()\n    {\n")
                .Append(Indent(operation.NativeBody, 8)).Append("\n        return 1;\n    });\n");
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendNativeCompositeOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingCompositeOperationDefinition operation)
    {
        var result = Find(api.CompositeResults, operation.ResultName, static value => value.Name);
        AppendNativeOperationHeader(builder, api, operation.NativeExport, "void", null, operation.Owners, operation.Values);
        foreach (var field in result.Fields)
        {
            _ = builder.Append(",\n    ").Append(ToNativeType(field.NativeType)).Append("* ")
                .Append(ToCamelCase(field.Name));
        }

        AppendNativeGuardedVoidBody(builder, operation.NativeBody);
    }

    private static void AppendNativeOwnedOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingOwnedOperationDefinition operation)
    {
        var owner = Find(api.Owners, operation.ResultOwnerName, static value => value.Name);
        AppendNativeOperationHeader(builder, api, operation.NativeExport, "void", owner, operation.Owners, operation.Values);
        AppendNativeGuardedVoidBody(builder, operation.NativeBody);
    }

    private static void AppendNativeScalarOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingScalarOperationDefinition operation)
    {
        AppendNativeOperationHeader(
            builder, api, operation.NativeExport, operation.NativeReturnType, null, operation.Owners, operation.Values);
        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n    return Guard<")
            .Append(operation.NativeReturnType).Append(">(error, ").Append(operation.NativeFailureExpression)
            .Append(", [&]()\n    {\n").Append(Indent(operation.NativeBody, 8)).Append("\n    });\n}\n\n");
    }

    private static void AppendNativeTwoPhaseOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingTwoPhaseOperationDefinition operation)
    {
        var owner = Find(api.Owners, operation.Owner.OwnerName, static value => value.Name);
        _ = builder.Append("extern \"C\" void ").Append(operation.CountExport).Append("(\n    const ")
            .Append(owner.NativeName).Append("* ").Append(operation.Owner.Name);
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append(",\n    std::size_t* ").Append(buffer.CountName);
        }

        AppendNativeGuardedVoidBody(builder, operation.CountNativeBody);
        _ = builder.Append("extern \"C\" void ").Append(operation.NativeExport).Append("(\n    const ")
            .Append(owner.NativeName).Append("* ").Append(operation.Owner.Name);
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append(",\n    ").Append(buffer.NativeElementType).Append("* ")
                .Append(BufferPointerName(buffer)).Append(",\n    std::size_t ")
                .Append(buffer.CountName);
        }

        AppendNativeGuardedVoidBody(builder, operation.NativeBody);
    }

    private static void AppendNativeOperationHeader(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        string export,
        string returnType,
        BindingOwnerDefinition? resultOwner,
        IReadOnlyList<BindingOwnerParameterDefinition> owners,
        IReadOnlyList<BindingValueParameterDefinition> values)
    {
        _ = builder.Append("extern \"C\" ").Append(returnType).Append(' ').Append(export).Append("(\n    ");
        var parameters = new List<string>();
        if (resultOwner is not null)
        {
            parameters.Add(resultOwner.NativeName + "* result");
        }

        parameters.AddRange(owners.Select(parameter =>
        {
            var owner = Find(api.Owners, parameter.OwnerName, static value => value.Name);
            return "const " + owner.NativeName + "* " + parameter.Name;
        }));
        parameters.AddRange(values.Select(parameter =>
            (parameter.PassByPointer ? "const " : "") + parameter.NativeType
            + (parameter.PassByPointer ? "* " : " ") + parameter.Name));
        _ = builder.AppendJoin(",\n    ", parameters);
    }

    private static void AppendNativeGuardedVoidBody(StringBuilder builder, string body)
    {
        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n    Guard<int>(error, 0, [&]()\n    {\n")
            .Append(Indent(body, 8)).Append("\n        return 1;\n    });\n}\n\n");
    }

    private static void AppendNativeErrorSupport(
        StringBuilder builder,
        BindingEmissionProfile profile,
        string unknownExceptionMessage)
    {
        var transport = BindingNativeErrorTransportEmitter.RenderInline(
            profile.NativeErrorClearExport,
            profile.NativeErrorSetter,
            "CopyText");
        var catches = BindingNativeErrorCatchEmitter.Render(
            profile.NativeErrorSetter,
            "error",
            unknownMessageExpression: "\"" + Escape(unknownExceptionMessage) + "\"");
        _ = builder.Append(transport).Append('\n')
            .Append("template<typename T, typename Callback>\n")
            .Append("static T Guard(NativeError* error, T fallback, Callback&& callback) noexcept\n")
            .Append("{\n    try { return callback(); }\n").Append(catches).Append("    return fallback;\n}\n\n")
            .Append('\n');
    }

    private static void AppendNativeDestroy(StringBuilder builder, BindingOwnerDefinition owner)
    {
        _ = builder.Append("extern \"C\" void ").Append(owner.DestroyExport).Append('(')
            .Append(owner.NativeName).Append("* value) noexcept\n{\n    if (value != nullptr) value->~")
            .Append(owner.NativeName).Append("();\n}\n\n");
    }

    private static string BufferPointerName(BindingTwoPhaseBufferDefinition buffer)
    {
        return buffer.PointerName ?? ToCamelCase(buffer.PropertyName) + "Pointer";
    }

    private static T Find<T>(IReadOnlyList<T> values, string name, Func<T, string> selector)
    {
        return values.Single(value => selector(value) == name);
    }

    private static string ToCamelCase(string value)
    {
        return char.ToLowerInvariant(value[0]) + value[1..];
    }

    private static string ToNativeType(string managedType)
    {
        return managedType switch
        {
            "byte" => "std::uint8_t",
            "double" => "double",
            _ => managedType,
        };
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string Indent(string value, int spaces)
    {
        var indentation = new string(' ', spaces);
        return indentation + value.Trim().Replace("\n", "\n" + indentation, StringComparison.Ordinal);
    }
}