// -----------------------------------------------------------------------
// <copyright file="BindingFiniteProfileEmitter.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

namespace TedToolkit.CppBindings.Generator.Semantics;

/// <summary>
/// Emits finite profile adapters from composable transport and result semantics.
/// </summary>
public static class BindingFiniteProfileEmitter
{
    /// <summary>
    /// Emits the managed half of one finite profile.
    /// </summary>
    /// <param name="api">The finite-profile API.</param>
    /// <param name="profile">The provider emission profile.</param>
    /// <param name="slots">The resolved native export slots.</param>
    /// <returns>The complete managed source.</returns>
    public static string RenderManaged(
        BindingFiniteProfileApi api,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        ArgumentNullException.ThrowIfNull(api);
        ArgumentNullException.ThrowIfNull(profile);
        ArgumentNullException.ThrowIfNull(slots);
        BindingFiniteProfileValidator.Validate(api, profile, slots);
        var builder = new StringBuilder("// <auto-generated />\n#pragma warning disable\n\n")
            .Append("using System.Runtime.InteropServices;\n\nnamespace ")
            .Append(profile.CSharpNamespace).Append(";\n\n");

        foreach (var status in api.Statuses)
        {
            AppendStatus(builder, status);
        }

        foreach (var value in api.ValueTypes)
        {
            AppendValueType(builder, value);
        }

        foreach (var result in api.OwnedResults)
        {
            AppendOwnedResult(builder, result);
        }

        foreach (var result in api.CompositeResults)
        {
            AppendCompositeResult(builder, result);
        }

        foreach (var owner in api.Owners)
        {
            AppendOwner(builder, api, owner, profile, slots);
        }

        foreach (var group in api.Operations
                     .Where(static operation => operation is not BindingBufferOwnerOperationDefinition)
                     .GroupBy(GetContainingType, StringComparer.Ordinal))
        {
            _ = builder.Append("public static unsafe class ").Append(group.Key).Append("\n{\n");
            var firstOperation = true;
            foreach (var operation in group)
            {
                if (!firstOperation)
                {
                    _ = builder.Append('\n');
                }

                AppendManagedOperation(builder, api, operation, profile, slots);
                firstOperation = false;
            }

            _ = builder.Append("}\n");
        }

        return builder.ToString();
    }

    /// <summary>
    /// Emits the native half of one finite profile.
    /// </summary>
    /// <param name="api">The finite-profile API.</param>
    /// <param name="profile">The provider emission profile.</param>
    /// <returns>The complete native source.</returns>
    public static string RenderNative(BindingFiniteProfileApi api, BindingEmissionProfile profile)
    {
        ArgumentNullException.ThrowIfNull(api);
        ArgumentNullException.ThrowIfNull(profile);
        BindingFiniteProfileValidator.Validate(api, profile);
        var builder = new StringBuilder("// <auto-generated />\n")
            .Append(api.NativePreamble.Trim()).Append("\n\n");
        AppendNativeErrorSupport(builder, profile, api.NativeUnknownExceptionMessage);
        foreach (var owner in api.Owners)
        {
            AppendNativeDestroy(builder, owner);
        }

        foreach (var operation in api.Operations)
        {
            AppendNativeOperation(builder, api, operation);
        }

        foreach (var export in api.AdditionalNativeExports)
        {
            _ = builder.Append("extern \"C\" ").Append(export.ReturnType).Append(' ')
                .Append(export.Name).Append('(').Append(export.Parameters).Append(") noexcept\n{\n")
                .Append(Indent(export.Body, 4)).Append("\n}\n\n");
        }

        return builder.ToString();
    }

    private static void AppendStatus(StringBuilder builder, BindingStatusDefinition status)
    {
        _ = builder.Append("public enum ").Append(status.Name).Append("\n{\n");
        foreach (var member in status.Members)
        {
            _ = builder.Append("    ").Append(member.Key).Append(" = ").Append(member.Value).Append(",\n");
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendValueType(StringBuilder builder, BindingValueTypeDefinition value)
    {
        _ = builder.Append("[StructLayout(LayoutKind.Sequential, Size = ").Append(value.Size)
            .Append(", Pack = ").Append(value.Alignment).Append(")]\npublic readonly struct ")
            .Append(value.Name).Append("\n{\n");
        foreach (var field in value.Fields)
        {
            _ = builder.Append("    private readonly ").Append(field.Type).Append(' ')
                .Append(ToCamelCase(field.Name)).Append(";\n");
        }

        _ = builder.Append("\n    public ").Append(value.Name).Append('(')
            .AppendJoin(", ", value.Fields.Select(field => field.Type + " " + ToCamelCase(field.Name)))
            .Append(")\n    {\n");
        foreach (var field in value.Fields)
        {
            var name = ToCamelCase(field.Name);
            _ = builder.Append("        this.").Append(name).Append(" = ").Append(name).Append(";\n");
        }

        _ = builder.Append("    }\n\n");
        foreach (var field in value.Fields)
        {
            _ = builder.Append("    public ").Append(field.Type).Append(' ').Append(field.Name)
                .Append(" => ").Append(ToCamelCase(field.Name)).Append(";\n\n");
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendOwnedResult(StringBuilder builder, BindingOwnedResultDefinition result)
    {
        _ = builder.Append("public sealed class ").Append(result.Name).Append("\n{\n")
            .Append("    internal ").Append(result.Name).Append('(').Append(result.StatusName)
            .Append(" code, global::TedToolkit.CppBindings.Owned<").Append(result.OwnerName)
            .Append(">? model)\n    {\n        ").Append(result.StatusProperty)
            .Append(" = code;\n        ").Append(result.OwnerProperty).Append(" = model;\n    }\n\n")
            .Append("    public ").Append(result.StatusName).Append(' ').Append(result.StatusProperty)
            .Append(" { get; }\n\n    public global::TedToolkit.CppBindings.Owned<")
            .Append(result.OwnerName).Append(">? ").Append(result.OwnerProperty).Append(" { get; }\n}\n\n");
    }

    private static void AppendCompositeResult(StringBuilder builder, BindingCompositeResultDefinition result)
    {
        if (result.Kind == BindingCompositeResultKind.RecordStruct)
        {
            _ = builder.Append("public readonly record struct ").Append(result.Name).Append('(')
                .AppendJoin(", ", result.Fields.Select(field => field.ManagedType + " " + field.Name))
                .Append(");\n\n");
            return;
        }

        _ = builder.Append("public sealed class ").Append(result.Name).Append("\n{\n    internal ")
            .Append(result.Name).Append('(')
            .AppendJoin(", ", result.Fields.Select(field => field.ManagedType + " " + ToCamelCase(field.Name)))
            .Append(")\n    {\n");
        foreach (var field in result.Fields)
        {
            _ = builder.Append("        ").Append(field.Name).Append(" = ")
                .Append(ToCamelCase(field.Name)).Append(";\n");
        }

        _ = builder.Append("    }\n\n");
        foreach (var field in result.Fields)
        {
            _ = builder.Append("    public ").Append(field.ManagedType).Append(' ').Append(field.Name)
                .Append(" { get; }\n\n");
        }

        foreach (var property in result.ComputedProperties ?? [])
        {
            _ = builder.Append("    public ").Append(property.Type).Append(' ').Append(property.Name)
                .Append(" => ").Append(property.Expression).Append(";\n\n");
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendOwner(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingOwnerDefinition owner,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        _ = builder.Append("[StructLayout(LayoutKind.Sequential, Size = ").Append(owner.Size)
            .Append(", Pack = ").Append(owner.Alignment).Append(")]\npublic unsafe struct ")
            .Append(owner.Name).Append(" : global::TedToolkit.CppBindings.ICppRaii\n{\n")
            .Append("    private nint storage;\n\n");
        foreach (var factory in api.Operations.OfType<BindingBufferOwnerOperationDefinition>()
                     .Where(operation => operation.OwnerName == owner.Name))
        {
            AppendBufferOwnerOperation(builder, owner, factory, profile, slots);
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendBufferOwnerOperation(
        StringBuilder builder,
        BindingOwnerDefinition owner,
        BindingBufferOwnerOperationDefinition operation,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        var returnType = operation.OwnedResultName
            ?? "global::TedToolkit.CppBindings.Owned<" + owner.Name + ">";
        _ = builder.Append("    public static ").Append(returnType).Append(' ')
            .Append(operation.MethodName).Append("(\n        ")
            .AppendJoin(",\n        ", operation.Buffers.Select(buffer =>
                "ReadOnlySpan<" + buffer.ElementType + "> " + buffer.Name))
            .Append(")\n    {\n");
        AppendBufferValidation(builder, operation.Buffers, 8);
        AppendOwnerConstructionStart(builder, owner, slots, 8);
        _ = builder.Append("            global::TedToolkit.CppBindings.NativeError error = default;\n");
        if (operation.OwnedResultName is not null)
        {
            _ = builder.Append("            ").Append(operation.NativeReturnType).Append(" code;\n");
        }

        _ = builder.Append("            fixed (").Append(owner.Name).Append("* resultPointer = &owner.Value)\n");
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append("            fixed (").Append(buffer.ElementType).Append("* ")
                .Append(BufferPointerName(buffer)).Append(" = ").Append(buffer.Name).Append(")\n");
        }

        _ = builder.Append("            {\n                ");
        if (operation.OwnedResultName is not null)
        {
            _ = builder.Append("code = ");
        }

        _ = builder.Append("((delegate* unmanaged[Cdecl]<").Append(owner.Name).Append("*, ")
            .AppendJoin(", ", operation.Buffers.SelectMany(static buffer =>
                new[] { buffer.ElementType + "*", "nuint", }))
            .Append(", global::TedToolkit.CppBindings.NativeError*, ").Append(operation.NativeReturnType)
            .Append(">)NativeApi.GetFunction(").Append(slots[operation.NativeExport]).Append("))(\n")
            .Append("                    resultPointer,\n                    ")
            .AppendJoin(",\n                    ", operation.Buffers.SelectMany(static buffer =>
                new[] { BufferPointerName(buffer), "(nuint)" + buffer.Name + ".Length", }))
            .Append(",\n                    &error);\n                ");
        AppendManagedErrorCheck(builder, profile, slots, 16);
        _ = builder.Append("            }\n\n");
        if (operation.OwnedResultName is not null)
        {
            _ = builder.Append("            if (code != (int)").Append(operation.StatusName).Append('.')
                .Append(operation.SuccessMember).Append(")\n            {\n                GC.SuppressFinalize(owner);\n")
                .Append("                return new ").Append(operation.OwnedResultName).Append("((")
                .Append(operation.StatusName).Append(")code, null);\n            }\n\n")
                .Append("            constructed = true;\n            return new ")
                .Append(operation.OwnedResultName).Append('(').Append(operation.StatusName).Append('.')
                .Append(operation.SuccessMember).Append(", owner);\n");
        }
        else
        {
            _ = builder.Append("            constructed = true;\n            return owner;\n");
        }

        AppendOwnerConstructionEnd(builder, 8);
        _ = builder.Append("    }\n");
    }

    private static void AppendManagedOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingFiniteOperationDefinition operation,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        switch (operation)
        {
            case BindingCompositeOperationDefinition composite:
                AppendCompositeOperation(builder, api, composite, profile, slots);
                break;

            case BindingOwnedOperationDefinition owned:
                AppendOwnedOperation(builder, api, owned, profile, slots);
                break;

            case BindingScalarOperationDefinition scalar:
                AppendScalarOperation(builder, api, scalar, profile, slots);
                break;

            case BindingTwoPhaseOperationDefinition twoPhase:
                AppendTwoPhaseOperation(builder, api, twoPhase, profile, slots);
                break;
        }
    }

    private static void AppendCompositeOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingCompositeOperationDefinition operation,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        var result = Find(api.CompositeResults, operation.ResultName, static value => value.Name);
        AppendMethodHeader(builder, operation.MethodName, result.Name, operation.Owners, operation.Values);
        AppendArgumentValidation(builder, operation.Owners, operation.Values);
        _ = builder.Append("        global::TedToolkit.CppBindings.NativeError error = default;\n");
        foreach (var field in result.Fields)
        {
            _ = builder.Append("        ").Append(field.NativeType).Append(' ').Append(ToCamelCase(field.Name))
                .Append(" = ").Append(field.InitialValue).Append(";\n");
        }

        AppendFixedOwners(builder, operation.Owners, api, 8);
        _ = builder.Append("        {\n            ((delegate* unmanaged[Cdecl]<")
            .AppendJoin(", ", operation.Owners.Select(owner => owner.OwnerName + "*")
                .Concat(operation.Values.Select(ValueFunctionPointerType))
                .Concat(result.Fields.Select(static field => field.NativeType + "*"))
                .Append("global::TedToolkit.CppBindings.NativeError*")
                .Append("void"))
            .Append(">)NativeApi.GetFunction(").Append(slots[operation.NativeExport]).Append("))(\n")
            .Append("                ").AppendJoin(", ", operation.Owners.Select(OwnerPointerName)
                .Concat(operation.Values.Select(ValueArgument))
                .Concat(result.Fields.Select(field => "&" + ToCamelCase(field.Name))))
            .Append(", &error);\n");
        AppendKeepAlive(builder, operation.Owners, 12);
        _ = builder.Append("        }\n\n        ");
        AppendManagedErrorCheck(builder, profile, slots, 8);
        _ = builder.Append("        return new ").Append(result.Name).Append('(')
            .AppendJoin(", ", result.Fields.Select(field => field.Projection.Replace(
                "$value", ToCamelCase(field.Name), StringComparison.Ordinal)))
            .Append(");\n    }\n");
    }

    private static void AppendOwnedOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingOwnedOperationDefinition operation,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        var owner = Find(api.Owners, operation.ResultOwnerName, static value => value.Name);
        AppendMethodHeader(
            builder,
            operation.MethodName,
            "global::TedToolkit.CppBindings.Owned<" + owner.Name + ">",
            operation.Owners,
            operation.Values);
        AppendArgumentValidation(builder, operation.Owners, operation.Values);
        AppendOwnerConstructionStart(builder, owner, slots, 8);
        _ = builder.Append("            global::TedToolkit.CppBindings.NativeError error = default;\n")
            .Append("            fixed (").Append(owner.Name).Append("* resultPointer = &owner.Value)\n");
        AppendFixedOwners(builder, operation.Owners, api, 12);
        _ = builder.Append("            {\n                ((delegate* unmanaged[Cdecl]<")
            .Append(owner.Name).Append("*, ")
            .AppendJoin(", ", operation.Owners.Select(parameter => parameter.OwnerName + "*")
                .Concat(operation.Values.Select(ValueFunctionPointerType))
                .Append("global::TedToolkit.CppBindings.NativeError*")
                .Append("void"))
            .Append(">)NativeApi.GetFunction(").Append(slots[operation.NativeExport]).Append("))(")
            .Append("resultPointer, ").AppendJoin(", ", operation.Owners.Select(OwnerPointerName)
                .Concat(operation.Values.Select(ValueArgument))).Append(", &error);\n");
        AppendKeepAlive(builder, operation.Owners, 16);
        _ = builder.Append("                ");
        AppendManagedErrorCheck(builder, profile, slots, 16);
        _ = builder.Append("            }\n\n            constructed = true;\n            return owner;\n");
        AppendOwnerConstructionEnd(builder, 8);
        _ = builder.Append("    }\n");
    }

    private static void AppendScalarOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingScalarOperationDefinition operation,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        AppendMethodHeader(builder, operation.MethodName, operation.ManagedReturnType, operation.Owners, operation.Values);
        AppendArgumentValidation(builder, operation.Owners, operation.Values);
        _ = builder.Append("        global::TedToolkit.CppBindings.NativeError error = default;\n");
        AppendFixedOwners(builder, operation.Owners, api, 8);
        _ = builder.Append("        {\n            var result = ((delegate* unmanaged[Cdecl]<")
            .AppendJoin(", ", operation.Owners.Select(parameter => parameter.OwnerName + "*")
                .Concat(operation.Values.Select(ValueFunctionPointerType))
                .Append("global::TedToolkit.CppBindings.NativeError*")
                .Append(operation.ManagedTransportType ?? operation.ManagedReturnType))
            .Append(">)NativeApi.GetFunction(").Append(slots[operation.NativeExport]).Append("))(")
            .AppendJoin(", ", operation.Owners.Select(OwnerPointerName).Concat(operation.Values.Select(ValueArgument)))
            .Append(", &error);\n");
        AppendKeepAlive(builder, operation.Owners, 12);
        _ = builder.Append("            ");
        AppendManagedErrorCheck(builder, profile, slots, 12);
        _ = builder.Append("            return ");
        if (operation.ManagedReturnType != (operation.ManagedTransportType ?? operation.ManagedReturnType))
        {
            _ = builder.Append('(').Append(operation.ManagedReturnType).Append(')');
        }

        _ = builder.Append("result;\n        }\n    }\n");
    }

    private static void AppendTwoPhaseOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingTwoPhaseOperationDefinition operation,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        AppendMethodHeader(
            builder,
            operation.MethodName,
            operation.ResultName,
            [operation.Owner,],
            []);
        AppendArgumentValidation(
            builder,
            [operation.Owner,],
            []);
        _ = builder.Append("        global::TedToolkit.CppBindings.NativeError error = default;\n");
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append("        nuint ").Append(buffer.CountName).Append(" = 0;\n");
        }

        AppendFixedOwners(
            builder,
            [operation.Owner,],
            api,
            8);
        _ = builder.Append("        {\n            ((delegate* unmanaged[Cdecl]<")
            .Append(operation.Owner.OwnerName).Append("*, ")
            .AppendJoin(", ", operation.Buffers.Select(static _ => "nuint*"))
            .Append(", global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(")
            .Append(slots[operation.CountExport]).Append("))(")
            .Append(OwnerPointerName(operation.Owner)).Append(", ")
            .AppendJoin(", ", operation.Buffers.Select(buffer => "&" + buffer.CountName))
            .Append(", &error);\n");
        AppendKeepAlive(
            builder,
            [operation.Owner,],
            12);
        _ = builder.Append("        }\n\n        ");
        AppendManagedErrorCheck(builder, profile, slots, 8);
        _ = builder.Append("        if (").AppendJoin(" || ", operation.Buffers.Select(buffer =>
                buffer.CountName + " > int.MaxValue"))
            .Append(")\n        {\n            throw new OverflowException(\"")
            .Append(Escape(operation.OverflowMessage)).Append("\");\n        }\n\n");
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append("        var ").Append(ToCamelCase(buffer.PropertyName)).Append(" = new ")
                .Append(buffer.ElementType).Append("[(int)").Append(buffer.CountName).Append("];\n");
        }

        AppendFixedOwners(
            builder,
            [operation.Owner,],
            api,
            8);
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append("        fixed (").Append(buffer.ElementType).Append("* ")
                .Append(BufferPointerName(buffer)).Append(" = ")
                .Append(ToCamelCase(buffer.PropertyName)).Append(")\n");
        }

        _ = builder.Append("        {\n            ((delegate* unmanaged[Cdecl]<")
            .Append(operation.Owner.OwnerName).Append("*, ")
            .AppendJoin(", ", operation.Buffers.SelectMany(static buffer =>
                new[] { buffer.ElementType + "*", "nuint", }))
            .Append(", global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(")
            .Append(slots[operation.NativeExport]).Append("))(").Append(OwnerPointerName(operation.Owner)).Append(", ")
            .AppendJoin(", ", operation.Buffers.SelectMany(buffer =>
                new[] { BufferPointerName(buffer), buffer.CountName, }))
            .Append(", &error);\n");
        AppendKeepAlive(
            builder,
            [operation.Owner,],
            12);
        _ = builder.Append("        }\n\n        ");
        AppendManagedErrorCheck(builder, profile, slots, 8);
        _ = builder.Append("        return new ").Append(operation.ResultName).Append('(')
            .AppendJoin(", ", operation.Buffers.Select(buffer => ToCamelCase(buffer.PropertyName)))
            .Append(");\n    }\n");
    }

    private static void AppendMethodHeader(
        StringBuilder builder,
        string methodName,
        string returnType,
        IReadOnlyList<BindingOwnerParameterDefinition> owners,
        IReadOnlyList<BindingValueParameterDefinition> values)
    {
        _ = builder.Append("    public static ").Append(returnType).Append(' ').Append(methodName).Append("(\n        ")
            .AppendJoin(",\n        ", owners.Select(owner =>
                (owner.IsExtensionReceiver ? "this " : "")
                + "global::TedToolkit.CppBindings.Owned<" + owner.OwnerName + "> " + owner.Name)
                .Concat(values.Select(value => value.ManagedType + " " + value.Name)))
            .Append(")\n    {\n");
    }

    private static void AppendArgumentValidation(
        StringBuilder builder,
        IReadOnlyList<BindingOwnerParameterDefinition> owners,
        IReadOnlyList<BindingValueParameterDefinition> values)
    {
        foreach (var owner in owners)
        {
            _ = builder.Append("        ArgumentNullException.ThrowIfNull(").Append(owner.Name).Append(");\n");
        }

        foreach (var value in values.Where(static value => value.RequireDefinedEnum))
        {
            _ = builder.Append("        if (!Enum.IsDefined(").Append(value.Name)
                .Append("))\n        {\n            throw new ArgumentOutOfRangeException(nameof(")
                .Append(value.Name).Append("));\n        }\n");
        }
    }

    private static void AppendOwnerConstructionStart(
        StringBuilder builder,
        BindingOwnerDefinition owner,
        IReadOnlyDictionary<string, int> slots,
        int spaces)
    {
        var indent = new string(' ', spaces);
        _ = builder.Append(indent).Append("var owner = new global::TedToolkit.CppBindings.Owned<")
            .Append(owner.Name).Append(">(\n").Append(indent).Append("    (delegate* unmanaged[Cdecl]<")
            .Append(owner.Name).Append("*, void>)NativeApi.GetFunction(")
            .Append(slots[owner.DestroyExport]).Append("));\n")
            .Append(indent).Append("var constructed = false;\n").Append(indent).Append("try\n")
            .Append(indent).Append("{\n");
    }

    private static void AppendOwnerConstructionEnd(StringBuilder builder, int spaces)
    {
        var indent = new string(' ', spaces);
        _ = builder.Append(indent).Append("}\n").Append(indent).Append("finally\n")
            .Append(indent).Append("{\n").Append(indent).Append("    if (!constructed)\n")
            .Append(indent).Append("    {\n").Append(indent).Append("        GC.SuppressFinalize(owner);\n")
            .Append(indent).Append("    }\n").Append(indent).Append("}\n");
    }

    private static void AppendFixedOwners(
        StringBuilder builder,
        IReadOnlyList<BindingOwnerParameterDefinition> owners,
        BindingFiniteProfileApi api,
        int spaces)
    {
        var indent = new string(' ', spaces);
        foreach (var parameter in owners)
        {
            _ = Find(api.Owners, parameter.OwnerName, static value => value.Name);
            _ = builder.Append(indent).Append("fixed (").Append(parameter.OwnerName).Append("* ")
                .Append(OwnerPointerName(parameter)).Append(" = &").Append(parameter.Name).Append(".Value)\n");
        }
    }

    private static void AppendKeepAlive(
        StringBuilder builder,
        IReadOnlyList<BindingOwnerParameterDefinition> owners,
        int spaces)
    {
        var indent = new string(' ', spaces);
        foreach (var owner in owners)
        {
            _ = builder.Append(indent).Append("GC.KeepAlive(").Append(owner.Name).Append(");\n");
        }
    }

    private static void AppendManagedErrorCheck(
        StringBuilder builder,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots,
        int spaces)
    {
        var indent = new string(' ', spaces);
        _ = builder.Append(profile.ManagedNativeErrorProjection)
            .Append(".ThrowIfFailed(\n").Append(indent).Append("    ref error,\n")
            .Append(indent).Append("    (delegate* unmanaged[Cdecl]<")
            .Append("global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(")
            .Append(slots[profile.NativeErrorClearExport]).Append("));\n");
    }

    private static void AppendBufferValidation(
        StringBuilder builder,
        IReadOnlyList<BindingBufferDefinition> buffers,
        int spaces)
    {
        var indent = new string(' ', spaces);
        foreach (var buffer in buffers)
        {
            _ = builder.Append(indent).Append("if (").Append(buffer.Name).Append(".Length % ")
                .Append(buffer.ElementsPerItem).Append(" != 0)\n").Append(indent).Append("{\n")
                .Append(indent).Append("    throw new ArgumentException(\"")
                .Append(Escape(buffer.LengthError)).Append("\", nameof(").Append(buffer.Name)
                .Append("));\n").Append(indent).Append("}\n\n");
        }

        var indexed = buffers.FirstOrDefault(static buffer => buffer.RequiresIndicesBelowFirstBufferItemCount);
        if (indexed is null)
        {
            return;
        }

        var source = buffers[0];
        _ = builder.Append(indent).Append("var itemCount = (nuint)(").Append(source.Name).Append(".Length / ")
            .Append(source.ElementsPerItem).Append(");\n").Append(indent).Append("foreach (var index in ")
            .Append(indexed.Name).Append(")\n").Append(indent).Append("{\n")
            .Append(indent).Append("    if (index >= itemCount)\n").Append(indent).Append("    {\n")
            .Append(indent).Append("        throw new ArgumentOutOfRangeException(nameof(")
            .Append(indexed.Name).Append("), index,\n").Append(indent).Append("            \"")
            .Append(Escape(indexed.IndexError)).Append("\");\n").Append(indent).Append("    }\n")
            .Append(indent).Append("}\n\n");
    }

    private static void AppendNativeOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingFiniteOperationDefinition operation)
    {
        switch (operation)
        {
            case BindingBufferOwnerOperationDefinition buffer:
                AppendNativeBufferOwnerOperation(builder, api, buffer);
                break;

            case BindingCompositeOperationDefinition composite:
                AppendNativeCompositeOperation(builder, api, composite);
                break;

            case BindingOwnedOperationDefinition owned:
                AppendNativeOwnedOperation(builder, api, owned);
                break;

            case BindingScalarOperationDefinition scalar:
                AppendNativeScalarOperation(builder, api, scalar);
                break;

            case BindingTwoPhaseOperationDefinition twoPhase:
                AppendNativeTwoPhaseOperation(builder, api, twoPhase);
                break;
        }
    }

    private static void AppendNativeBufferOwnerOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingBufferOwnerOperationDefinition operation)
    {
        var owner = Find(api.Owners, operation.OwnerName, static value => value.Name);
        _ = builder.Append("extern \"C\" ").Append(operation.NativeReturnType).Append(' ')
            .Append(operation.NativeExport).Append("(\n    ").Append(owner.NativeName).Append("* result");
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append(",\n    const ").Append(buffer.NativeElementType).Append("* ")
                .Append(ToCamelCase(buffer.Name)).Append(",\n    std::size_t ")
                .Append(ToCamelCase(buffer.Name)).Append("Count");
        }

        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n");
        if (operation.OwnedResultName is not null)
        {
            _ = builder.Append("    return Guard<").Append(operation.NativeReturnType).Append(">(error, ")
                .Append(operation.NativeFailureExpression).Append(", [&]()\n    {\n")
                .Append(Indent(operation.NativeBody, 8)).Append("\n    });\n");
        }
        else
        {
            _ = builder.Append("    Guard<int>(error, 0, [&]()\n    {\n")
                .Append(Indent(operation.NativeBody, 8)).Append("\n        return 1;\n    });\n");
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendNativeCompositeOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingCompositeOperationDefinition operation)
    {
        var result = Find(api.CompositeResults, operation.ResultName, static value => value.Name);
        AppendNativeOperationHeader(builder, api, operation.NativeExport, "void", null, operation.Owners, operation.Values);
        foreach (var field in result.Fields)
        {
            _ = builder.Append(",\n    ").Append(ToNativeType(field.NativeType)).Append("* ")
                .Append(ToCamelCase(field.Name));
        }

        AppendNativeGuardedVoidBody(builder, operation.NativeBody);
    }

    private static void AppendNativeOwnedOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingOwnedOperationDefinition operation)
    {
        var owner = Find(api.Owners, operation.ResultOwnerName, static value => value.Name);
        AppendNativeOperationHeader(builder, api, operation.NativeExport, "void", owner, operation.Owners, operation.Values);
        AppendNativeGuardedVoidBody(builder, operation.NativeBody);
    }

    private static void AppendNativeScalarOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingScalarOperationDefinition operation)
    {
        AppendNativeOperationHeader(
            builder, api, operation.NativeExport, operation.NativeReturnType, null, operation.Owners, operation.Values);
        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n    return Guard<")
            .Append(operation.NativeReturnType).Append(">(error, ").Append(operation.NativeFailureExpression)
            .Append(", [&]()\n    {\n").Append(Indent(operation.NativeBody, 8)).Append("\n    });\n}\n\n");
    }

    private static void AppendNativeTwoPhaseOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingTwoPhaseOperationDefinition operation)
    {
        var owner = Find(api.Owners, operation.Owner.OwnerName, static value => value.Name);
        _ = builder.Append("extern \"C\" void ").Append(operation.CountExport).Append("(\n    const ")
            .Append(owner.NativeName).Append("* ").Append(operation.Owner.Name);
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append(",\n    std::size_t* ").Append(buffer.CountName);
        }

        AppendNativeGuardedVoidBody(builder, operation.CountNativeBody);
        _ = builder.Append("extern \"C\" void ").Append(operation.NativeExport).Append("(\n    const ")
            .Append(owner.NativeName).Append("* ").Append(operation.Owner.Name);
        foreach (var buffer in operation.Buffers)
        {
            _ = builder.Append(",\n    ").Append(buffer.NativeElementType).Append("* ")
                .Append(BufferPointerName(buffer)).Append(",\n    std::size_t ")
                .Append(buffer.CountName);
        }

        AppendNativeGuardedVoidBody(builder, operation.NativeBody);
    }

    private static void AppendNativeOperationHeader(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        string export,
        string returnType,
        BindingOwnerDefinition? resultOwner,
        IReadOnlyList<BindingOwnerParameterDefinition> owners,
        IReadOnlyList<BindingValueParameterDefinition> values)
    {
        _ = builder.Append("extern \"C\" ").Append(returnType).Append(' ').Append(export).Append("(\n    ");
        var parameters = new List<string>();
        if (resultOwner is not null)
        {
            parameters.Add(resultOwner.NativeName + "* result");
        }

        parameters.AddRange(owners.Select(parameter =>
        {
            var owner = Find(api.Owners, parameter.OwnerName, static value => value.Name);
            return "const " + owner.NativeName + "* " + parameter.Name;
        }));
        parameters.AddRange(values.Select(parameter =>
            (parameter.PassByPointer ? "const " : "") + parameter.NativeType
            + (parameter.PassByPointer ? "* " : " ") + parameter.Name));
        _ = builder.AppendJoin(",\n    ", parameters);
    }

    private static void AppendNativeGuardedVoidBody(StringBuilder builder, string body)
    {
        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n    Guard<int>(error, 0, [&]()\n    {\n")
            .Append(Indent(body, 8)).Append("\n        return 1;\n    });\n}\n\n");
    }

    private static void AppendNativeErrorSupport(
        StringBuilder builder,
        BindingEmissionProfile profile,
        string unknownExceptionMessage)
    {
        var catches = BindingNativeErrorCatchEmitter.Render(
            profile.NativeErrorSetter,
            "error",
            unknownMessageExpression: "\"" + Escape(unknownExceptionMessage) + "\"");
        _ = builder.Append("struct NativeError\n{\n    int Kind;\n    char* TypeName;\n    char* Message;\n")
            .Append("    char* StackTrace;\n};\n\n")
            .Append("static char* CopyText(const char* value) noexcept\n{\n")
            .Append("    if (value == nullptr) return nullptr;\n    const auto length = std::strlen(value) + 1;\n")
            .Append("    auto* copy = static_cast<char*>(std::malloc(length));\n")
            .Append("    if (copy != nullptr) std::memcpy(copy, value, length);\n    return copy;\n}\n\n")
            .Append("static void ").Append(profile.NativeErrorSetter)
            .Append("(NativeError* error, int kind, const char* type, const char* message) noexcept\n{\n")
            .Append("    if (error == nullptr) return;\n    error->Kind = kind;\n")
            .Append("    error->TypeName = CopyText(type);\n")
            .Append("    error->Message = CopyText(message);\n    error->StackTrace = nullptr;\n}\n\n")
            .Append("template<typename T, typename Callback>\n")
            .Append("static T Guard(NativeError* error, T fallback, Callback&& callback) noexcept\n")
            .Append("{\n    try { return callback(); }\n").Append(catches).Append("    return fallback;\n}\n\n")
            .Append("extern \"C\" void ").Append(profile.NativeErrorClearExport)
            .Append("(NativeError* error) noexcept\n{\n    if (error == nullptr) return;\n")
            .Append("    std::free(error->TypeName);\n    std::free(error->Message);\n")
            .Append("    std::free(error->StackTrace);\n")
            .Append("    *error = {};\n}\n\n");
    }

    private static void AppendNativeDestroy(StringBuilder builder, BindingOwnerDefinition owner)
    {
        _ = builder.Append("extern \"C\" void ").Append(owner.DestroyExport).Append('(')
            .Append(owner.NativeName).Append("* value) noexcept\n{\n    if (value != nullptr) value->~")
            .Append(owner.NativeName).Append("();\n}\n\n");
    }

    private static string GetContainingType(BindingFiniteOperationDefinition operation)
    {
        return operation switch
        {
            BindingCompositeOperationDefinition value => value.ContainingType,
            BindingOwnedOperationDefinition value => value.ContainingType,
            BindingScalarOperationDefinition value => value.ContainingType,
            BindingTwoPhaseOperationDefinition value => value.ContainingType,
            _ => throw new InvalidOperationException("A buffer owner operation is emitted on its owner type."),
        };
    }

    private static string OwnerPointerName(BindingOwnerParameterDefinition owner)
    {
        return owner.Name + "Pointer";
    }

    private static string BufferPointerName(BindingBufferDefinition buffer)
    {
        return buffer.PointerName ?? ToCamelCase(buffer.Name) + "Pointer";
    }

    private static string BufferPointerName(BindingTwoPhaseBufferDefinition buffer)
    {
        return buffer.PointerName ?? ToCamelCase(buffer.PropertyName) + "Pointer";
    }

    private static string ValueFunctionPointerType(BindingValueParameterDefinition value)
    {
        return (value.ManagedTransportType ?? value.ManagedType) + (value.PassByPointer ? "*" : "");
    }

    private static string ValueArgument(BindingValueParameterDefinition value)
    {
        var argument = value.ManagedArgumentExpression.Replace("$value", value.Name, StringComparison.Ordinal);
        return value.PassByPointer ? "&" + argument : argument;
    }

    private static T Find<T>(IReadOnlyList<T> values, string name, Func<T, string> selector)
    {
        return values.Single(value => selector(value) == name);
    }

    private static string ToCamelCase(string value)
    {
        return char.ToLowerInvariant(value[0]) + value[1..];
    }

    private static string ToNativeType(string managedType)
    {
        return managedType switch
        {
            "byte" => "std::uint8_t",
            "double" => "double",
            _ => managedType,
        };
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string Indent(string value, int spaces)
    {
        var indentation = new string(' ', spaces);
        return indentation + value.Trim().Replace("\n", "\n" + indentation, StringComparison.Ordinal);
    }
}