// -----------------------------------------------------------------------
// <copyright file="BindingFiniteProfileEmitter.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

namespace TedToolkit.CppBindings.Generator.Semantics;

/// <summary>
/// Emits finite profile adapters from explicit buffer, ownership, and composite-result semantics.
/// </summary>
public static class BindingFiniteProfileEmitter
{
    /// <summary>
    /// Emits the managed half of one finite profile.
    /// </summary>
    /// <param name="api">The finite profile model.</param>
    /// <param name="profile">The provider emission profile.</param>
    /// <param name="slots">The shared native export slot map.</param>
    /// <returns>The complete managed source.</returns>
    public static string RenderManaged(
        BindingFiniteProfileApi api,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        ArgumentNullException.ThrowIfNull(api);
        ArgumentNullException.ThrowIfNull(profile);
        ArgumentNullException.ThrowIfNull(slots);
        Validate(api, profile, slots);
        var builder = new StringBuilder("// <auto-generated />\n#pragma warning disable\n\n")
            .Append("using System.Runtime.InteropServices;\n\nnamespace ")
            .Append(profile.CSharpNamespace).Append(";\n\n");
        AppendStatus(builder, api.Status);
        AppendValueType(builder, api.ValueType);
        AppendOwnedResult(builder, api);
        AppendCompositeResult(builder, api.CompositeResult);
        AppendOwner(builder, api, profile, slots);
        AppendCompositeOperation(builder, api, profile, slots);
        return builder.ToString();
    }

    /// <summary>
    /// Emits the native half of one finite profile.
    /// </summary>
    /// <param name="api">The finite profile model.</param>
    /// <param name="profile">The provider emission profile.</param>
    /// <returns>The complete native source.</returns>
    public static string RenderNative(BindingFiniteProfileApi api, BindingEmissionProfile profile)
    {
        ArgumentNullException.ThrowIfNull(api);
        ArgumentNullException.ThrowIfNull(profile);
        var builder = new StringBuilder("// <auto-generated />\n")
            .Append(api.NativePreamble.Trim()).Append("\n\n");
        AppendNativeErrorSupport(builder, profile, api.NativeUnknownExceptionMessage);
        AppendNativeDestroy(builder, api.Owner);
        AppendNativeFactory(builder, api);
        AppendNativeCompositeOperation(builder, api);
        foreach (var export in api.AdditionalNativeExports)
        {
            _ = builder.Append("extern \"C\" ").Append(export.ReturnType).Append(' ')
                .Append(export.Name).Append('(').Append(export.Parameters).Append(") noexcept\n{\n")
                .Append(Indent(export.Body, 4)).Append("\n}\n\n");
        }

        return builder.ToString();
    }

    private static void AppendStatus(StringBuilder builder, BindingStatusDefinition status)
    {
        _ = builder.Append("public enum ").Append(status.Name).Append("\n{\n");
        foreach (var member in status.Members)
        {
            _ = builder.Append("    ").Append(member.Key).Append(" = ").Append(member.Value).Append(",\n");
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendValueType(StringBuilder builder, BindingValueTypeDefinition value)
    {
        _ = builder.Append("[StructLayout(LayoutKind.Sequential, Size = ").Append(value.Size)
            .Append(", Pack = ").Append(value.Alignment).Append(")]\npublic readonly struct ")
            .Append(value.Name).Append("\n{\n");
        foreach (var field in value.Fields)
        {
            _ = builder.Append("    private readonly ").Append(field.Type).Append(' ')
                .Append(ToCamelCase(field.Name)).Append(";\n");
        }

        _ = builder.Append("\n    public ").Append(value.Name).Append('(')
            .AppendJoin(", ", value.Fields.Select(field => field.Type + " " + ToCamelCase(field.Name)))
            .Append(")\n    {\n");
        foreach (var field in value.Fields)
        {
            var name = ToCamelCase(field.Name);
            _ = builder.Append("        this.").Append(name).Append(" = ").Append(name).Append(";\n");
        }

        _ = builder.Append("    }\n\n");
        foreach (var field in value.Fields)
        {
            _ = builder.Append("    public ").Append(field.Type).Append(' ').Append(field.Name)
                .Append(" => ").Append(ToCamelCase(field.Name)).Append(";\n\n");
        }

        _ = builder.Append("}\n\n");
    }

    private static void AppendOwnedResult(StringBuilder builder, BindingFiniteProfileApi api)
    {
        var result = api.OwnedResult;
        _ = builder.Append("public sealed class ").Append(result.Name).Append("\n{\n")
            .Append("    internal ").Append(result.Name).Append('(').Append(api.Status.Name)
            .Append(" code, global::TedToolkit.CppBindings.Owned<").Append(api.Owner.Name)
            .Append(">? model)\n    {\n        ").Append(result.StatusProperty)
            .Append(" = code;\n        ").Append(result.OwnerProperty).Append(" = model;\n    }\n\n")
            .Append("    public ").Append(api.Status.Name).Append(' ').Append(result.StatusProperty)
            .Append(" { get; }\n\n    public global::TedToolkit.CppBindings.Owned<")
            .Append(api.Owner.Name).Append(">? ").Append(result.OwnerProperty).Append(" { get; }\n}\n\n");
    }

    private static void AppendCompositeResult(StringBuilder builder, BindingCompositeResultDefinition result)
    {
        _ = builder.Append("public readonly record struct ").Append(result.Name).Append('(')
            .AppendJoin(", ", result.Fields.Select(field => field.ManagedType + " " + field.Name))
            .Append(");\n\n");
    }

    private static void AppendOwner(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        var owner = api.Owner;
        var factory = api.Factory;
        _ = builder.Append("[StructLayout(LayoutKind.Sequential, Size = ").Append(owner.Size)
            .Append(", Pack = ").Append(owner.Alignment).Append(")]\npublic unsafe struct ")
            .Append(owner.Name).Append(" : global::TedToolkit.CppBindings.ICppRaii\n{\n")
            .Append("    private nint storage;\n\n    public static ").Append(api.OwnedResult.Name)
            .Append(' ').Append(factory.MethodName).Append("(\n        ")
            .AppendJoin(",\n        ", factory.Buffers.Select(buffer =>
                "ReadOnlySpan<" + buffer.ElementType + "> " + buffer.Name))
            .Append(")\n    {\n");
        AppendBufferValidation(builder, factory.Buffers);
        _ = builder.Append("        var owner = new global::TedToolkit.CppBindings.Owned<")
            .Append(owner.Name).Append(">(\n            (delegate* unmanaged[Cdecl]<")
            .Append(owner.Name).Append("*, void>)NativeApi.GetFunction(")
            .Append(slots[owner.DestroyExport]).Append("));\n")
            .Append("        var constructed = false;\n        try\n        {\n")
            .Append("            global::TedToolkit.CppBindings.NativeError error = default;\n")
            .Append("            int code;\n");
        AppendFixedBuffers(builder, api);
        _ = builder.Append("            {\n                code = ((delegate* unmanaged[Cdecl]<")
            .Append(owner.Name).Append("*, ")
            .AppendJoin(", ", factory.Buffers.SelectMany(static buffer =>
                new[] { buffer.ElementType + "*", "nuint", }))
            .Append(", global::TedToolkit.CppBindings.NativeError*, int>)NativeApi.GetFunction(")
            .Append(slots[factory.NativeExport]).Append("))(\n                    resultPointer,\n                    ")
            .AppendJoin(",\n                    ", factory.Buffers.SelectMany(static buffer =>
                new[] { ToCamelCase(buffer.Name) + "Pointer", "(nuint)" + buffer.Name + ".Length", }))
            .Append(",\n                    &error);\n                ")
            .Append(profile.ManagedNativeErrorProjection)
            .Append(".ThrowIfFailed(\n                    ref error,\n")
            .Append("                    (delegate* unmanaged[Cdecl]<")
            .Append("global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(")
            .Append(slots[profile.NativeErrorClearExport]).Append("));\n            }\n\n")
            .Append("            if (code != (int)").Append(api.Status.Name).Append('.')
            .Append(factory.SuccessMember).Append(")\n            {\n                GC.SuppressFinalize(owner);\n")
            .Append("                return new ").Append(api.OwnedResult.Name).Append("((")
            .Append(api.Status.Name).Append(")code, null);\n            }\n\n")
            .Append("            constructed = true;\n            return new ").Append(api.OwnedResult.Name)
            .Append('(').Append(api.Status.Name).Append('.').Append(factory.SuccessMember)
            .Append(", owner);\n        }\n        finally\n        {\n            if (!constructed)\n")
            .Append("            {\n                GC.SuppressFinalize(owner);\n")
            .Append("            }\n        }\n    }\n}\n\n");
    }

    private static void AppendBufferValidation(StringBuilder builder, IReadOnlyList<BindingBufferDefinition> buffers)
    {
        foreach (var buffer in buffers)
        {
            _ = builder.Append("        if (").Append(buffer.Name).Append(".Length % ")
                .Append(buffer.ElementsPerItem).Append(" != 0)\n        {\n            throw new ArgumentException(\"")
                .Append(Escape(buffer.LengthError)).Append("\", nameof(").Append(buffer.Name)
                .Append("));\n        }\n\n");
        }

        var indexed = buffers.FirstOrDefault(static buffer => buffer.RequiresIndicesBelowFirstBufferItemCount);
        if (indexed is null)
        {
            return;
        }

        var source = buffers[0];
        _ = builder.Append("        var itemCount = (nuint)(").Append(source.Name).Append(".Length / ")
            .Append(source.ElementsPerItem).Append(");\n        foreach (var index in ").Append(indexed.Name)
            .Append(")\n        {\n            if (index >= itemCount)\n            {\n")
            .Append("                throw new ArgumentOutOfRangeException(nameof(").Append(indexed.Name)
            .Append("), index,\n                    \"").Append(Escape(indexed.IndexError)).Append("\");\n")
            .Append("            }\n        }\n\n");
    }

    private static void AppendFixedBuffers(StringBuilder builder, BindingFiniteProfileApi api)
    {
        _ = builder.Append("            fixed (").Append(api.Owner.Name)
            .Append("* resultPointer = &owner.Value)\n");
        foreach (var buffer in api.Factory.Buffers)
        {
            _ = builder.Append("            fixed (").Append(buffer.ElementType).Append("* ")
                .Append(ToCamelCase(buffer.Name)).Append("Pointer = ").Append(buffer.Name).Append(")\n");
        }
    }

    private static void AppendCompositeOperation(
        StringBuilder builder,
        BindingFiniteProfileApi api,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        var operation = api.CompositeOperation;
        var fields = api.CompositeResult.Fields;
        _ = builder.Append("public static unsafe class ").Append(operation.ContainingType).Append("\n{\n")
            .Append("    public static ").Append(api.CompositeResult.Name).Append(' ').Append(operation.MethodName)
            .Append("(\n        global::TedToolkit.CppBindings.Owned<").Append(api.Owner.Name).Append("> ")
            .Append(operation.FirstOwnerParameter).Append(",\n        global::TedToolkit.CppBindings.Owned<")
            .Append(api.Owner.Name).Append("> ").Append(operation.SecondOwnerParameter).Append(",\n        ")
            .Append(api.ValueType.Name).Append(' ').Append(operation.ValueParameter).Append(")\n    {\n")
            .Append("        ArgumentNullException.ThrowIfNull(").Append(operation.FirstOwnerParameter).Append(");\n")
            .Append("        ArgumentNullException.ThrowIfNull(").Append(operation.SecondOwnerParameter).Append(");\n")
            .Append("        global::TedToolkit.CppBindings.NativeError error = default;\n");
        foreach (var field in fields)
        {
            _ = builder.Append("        ").Append(field.NativeType).Append(' ').Append(ToCamelCase(field.Name))
                .Append(" = ").Append(field.InitialValue).Append(";\n");
        }

        _ = builder.Append("        fixed (").Append(api.Owner.Name).Append("* firstPointer = &")
            .Append(operation.FirstOwnerParameter).Append(".Value)\n        fixed (").Append(api.Owner.Name)
            .Append("* secondPointer = &").Append(operation.SecondOwnerParameter).Append(".Value)\n        {\n")
            .Append("            ((delegate* unmanaged[Cdecl]<").Append(api.Owner.Name).Append("*, ")
            .Append(api.Owner.Name).Append("*, ").Append(api.ValueType.Name).Append("*, ")
            .AppendJoin(", ", fields.Select(static field => field.NativeType + "*"))
            .Append(", global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(")
            .Append(slots[operation.NativeExport]).Append("))(\n                firstPointer, secondPointer, &")
            .Append(operation.ValueParameter).Append(", ")
            .AppendJoin(", ", fields.Select(field => "&" + ToCamelCase(field.Name)))
            .Append(", &error);\n            GC.KeepAlive(").Append(operation.FirstOwnerParameter)
            .Append(");\n            GC.KeepAlive(").Append(operation.SecondOwnerParameter)
            .Append(");\n        }\n\n        ")
            .Append(profile.ManagedNativeErrorProjection)
            .Append(".ThrowIfFailed(\n            ref error,\n")
            .Append("            (delegate* unmanaged[Cdecl]<")
            .Append("global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(")
            .Append(slots[profile.NativeErrorClearExport]).Append("));\n        return new ")
            .Append(api.CompositeResult.Name).Append('(')
            .AppendJoin(", ", fields.Select(field => field.Projection.Replace(
                "$value",
                ToCamelCase(field.Name),
                StringComparison.Ordinal)))
            .Append(");\n    }\n}\n");
    }

    private static void AppendNativeErrorSupport(
        StringBuilder builder,
        BindingEmissionProfile profile,
        string unknownExceptionMessage)
    {
        var catches = BindingNativeErrorCatchEmitter.Render(
            profile.NativeErrorSetter,
            "error",
            unknownMessageExpression: "\"" + Escape(unknownExceptionMessage) + "\"");
        _ = builder.Append("struct NativeError\n{\n    int Kind;\n    char* TypeName;\n    char* Message;\n")
            .Append("    char* StackTrace;\n};\n\n")
            .Append("static char* CopyText(const char* value) noexcept\n{\n")
            .Append("    if (value == nullptr) return nullptr;\n    const auto length = std::strlen(value) + 1;\n")
            .Append("    auto* copy = static_cast<char*>(std::malloc(length));\n")
            .Append("    if (copy != nullptr) std::memcpy(copy, value, length);\n    return copy;\n}\n\n")
            .Append("static void ").Append(profile.NativeErrorSetter)
            .Append("(NativeError* error, int kind, const char* type, const char* message) noexcept\n{\n")
            .Append("    if (error == nullptr) return;\n    error->Kind = kind;\n")
            .Append("    error->TypeName = CopyText(type);\n")
            .Append("    error->Message = CopyText(message);\n    error->StackTrace = nullptr;\n}\n\n")
            .Append("template<typename T, typename Callback>\n")
            .Append("static T Guard(NativeError* error, T fallback, Callback&& callback) noexcept\n")
            .Append("{\n    try { return callback(); }\n").Append(catches).Append("    return fallback;\n}\n\n")
            .Append("extern \"C\" void ").Append(profile.NativeErrorClearExport)
            .Append("(NativeError* error) noexcept\n{\n    if (error == nullptr) return;\n")
            .Append("    std::free(error->TypeName);\n    std::free(error->Message);\n")
            .Append("    std::free(error->StackTrace);\n")
            .Append("    *error = {};\n}\n\n");
    }

    private static void AppendNativeDestroy(StringBuilder builder, BindingOwnerDefinition owner)
    {
        _ = builder.Append("extern \"C\" void ").Append(owner.DestroyExport).Append('(')
            .Append(owner.NativeName).Append("* value) noexcept\n{\n    if (value != nullptr) value->~")
            .Append(owner.NativeName).Append("();\n}\n\n");
    }

    private static void AppendNativeFactory(StringBuilder builder, BindingFiniteProfileApi api)
    {
        _ = builder.Append("extern \"C\" int ").Append(api.Factory.NativeExport).Append("(\n    ")
            .Append(api.Owner.NativeName).Append("* result");
        foreach (var buffer in api.Factory.Buffers)
        {
            _ = builder.Append(",\n    const ").Append(buffer.NativeElementType).Append("* ")
                .Append(ToCamelCase(buffer.Name)).Append(",\n    std::size_t ")
                .Append(ToCamelCase(buffer.Name)).Append("Count");
        }

        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n    return Guard<int>(error, ")
            .Append(api.Factory.NativeFailureExpression).Append(", [&]()\n    {\n")
            .Append(Indent(api.FactoryBody, 8)).Append("\n    });\n}\n\n");
    }

    private static void AppendNativeCompositeOperation(StringBuilder builder, BindingFiniteProfileApi api)
    {
        _ = builder.Append("extern \"C\" void ").Append(api.CompositeOperation.NativeExport).Append("(\n    const ")
            .Append(api.Owner.NativeName).Append("* first,\n    const ").Append(api.Owner.NativeName)
            .Append("* second,\n    const ").Append(api.ValueType.NativeName).Append("* ")
            .Append(api.CompositeOperation.ValueParameter);
        foreach (var field in api.CompositeResult.Fields)
        {
            _ = builder.Append(",\n    ").Append(ToNativeType(field.NativeType)).Append("* ")
                .Append(ToCamelCase(field.Name));
        }

        _ = builder.Append(",\n    NativeError* error) noexcept\n{\n    Guard<int>(error, 0, [&]()\n    {\n")
            .Append(Indent(api.CompositeOperationBody, 8)).Append("\n        return 1;\n    });\n}\n\n");
    }

    private static void Validate(
        BindingFiniteProfileApi api,
        BindingEmissionProfile profile,
        IReadOnlyDictionary<string, int> slots)
    {
        var exports = api.AdditionalNativeExports.Select(static item => item.Name)
            .Append(api.Owner.DestroyExport)
            .Append(api.Factory.NativeExport)
            .Append(api.CompositeOperation.NativeExport)
            .Append(profile.NativeErrorClearExport)
            .ToArray();
        if (!exports.Order(StringComparer.Ordinal).SequenceEqual(
                api.NativeExportOrder.Order(StringComparer.Ordinal),
                StringComparer.Ordinal))
        {
            throw new InvalidOperationException(
                "A finite profile export order must contain every emitted native operation exactly once.");
        }

        foreach (var export in exports)
        {
            if (slots.ContainsKey(export))
            {
                continue;
            }

            throw new InvalidOperationException(
                $"Finite profile export '{export}' has no shared function-table slot.");
        }

        if (api.Factory.Buffers.Count > 0)
        {
            return;
        }

        throw new InvalidOperationException(
            "A finite profile factory requires at least one buffer and one native slot.");
    }

    private static string ToCamelCase(string value)
    {
        return char.ToLowerInvariant(value[0]) + value[1..];
    }

    private static string ToNativeType(string managedType)
    {
        return managedType switch
        {
            "byte" => "std::uint8_t",
            "double" => "double",
            _ => managedType,
        };
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string Indent(string value, int spaces)
    {
        var indentation = new string(' ', spaces);
        return indentation + value.Trim().Replace("\n", "\n" + indentation, StringComparison.Ordinal);
    }
}