// <auto-generated />
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Object.h>
#include <CGAL/exceptions.h>

#include <atomic>
#include <cstdlib>
#include <cstring>
#include <exception>
#include <new>
#include <optional>
#include <stdexcept>
#include <variant>

struct NativeError
{
    int Kind;
    char* TypeName;
    char* Message;
    char* StackTrace;
};

struct NativeResult
{
    int Tag;
    double AX;
    double AY;
    double BX;
    double BY;
};

namespace
{
using Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
using Point = Kernel::Point_2;
using Segment = Kernel::Segment_2;
using Variant = std::variant<Point, Segment, int>;

std::atomic<int> diagnosticClearCount{};
std::atomic<int> containerCreateCount{};
std::atomic<int> containerDestroyCount{};
std::atomic<int> alternativeTransferCount{};

char* CopyText(const char* value) noexcept
{
    if (value == nullptr)
    {
        return nullptr;
    }

    const auto size = std::strlen(value) + 1;
    auto* copy = static_cast<char*>(std::malloc(size));
    if (copy != nullptr)
    {
        std::memcpy(copy, value, size);
    }

    return copy;
}

void SetError(
    NativeError* error,
    int kind,
    const char* typeName,
    const char* message,
    const char* stackTrace) noexcept
{
    if (error == nullptr)
    {
        return;
    }

    error->Kind = kind;
    error->TypeName = CopyText(typeName);
    error->Message = CopyText(message);
    error->StackTrace = CopyText(stackTrace);
}

std::string FailureStack(const CGAL::Failure_exception& failure)
{
    return failure.filename() + ":" + std::to_string(failure.line_number());
}

struct FixtureBadAlloc final : std::bad_alloc
{
    const char* what() const noexcept override
    {
        return "fixture bad allocation";
    }
};

void ThrowSelectedFailure(int scenario)
{
    switch (scenario)
    {
        case 1:
            throw std::invalid_argument("fixture invalid argument");
        case 2:
            throw std::out_of_range("fixture out of range");
        case 3:
            throw FixtureBadAlloc();
        case 4:
            throw std::overflow_error("fixture overflow");
        case 5:
            throw std::underflow_error("fixture underflow");
        case 6:
            throw std::runtime_error("fixture standard exception");
        case 7:
            throw 42;
        case 10:
            throw CGAL::Error_exception("CGAL", "fixture error", __FILE__, __LINE__);
        case 11:
            throw CGAL::Precondition_exception("CGAL", "false", __FILE__, __LINE__, "fixture precondition");
        case 12:
            throw CGAL::Postcondition_exception("CGAL", "false", __FILE__, __LINE__, "fixture postcondition");
        case 13:
            throw CGAL::Assertion_exception("CGAL", "false", __FILE__, __LINE__, "fixture assertion");
        case 14:
            throw CGAL::Test_exception("CGAL", "false", __FILE__, __LINE__, "fixture test");
        case 15:
            throw CGAL::Warning_exception("CGAL", "false", __FILE__, __LINE__, "fixture warning");
        case 16:
            throw CGAL::Failure_exception("CGAL", "false", __FILE__, __LINE__, "fixture failure");
        default:
            return;
    }
}

struct TrackedVariant
{
    explicit TrackedVariant(int scenario)
    {
        ++containerCreateCount;
        switch (scenario)
        {
            case 1:
                Value.emplace(Point(1.0, 2.0));
                break;
            case 2:
                Value.emplace(Segment(Point(1.0, 2.0), Point(3.0, 4.0)));
                break;
            case 3:
                Value.emplace(42);
                break;
            default:
                break;
        }
    }

    ~TrackedVariant()
    {
        ++containerDestroyCount;
    }

    std::optional<Variant> Value;
};

struct TrackedObject
{
    explicit TrackedObject(int scenario)
    {
        ++containerCreateCount;
        switch (scenario)
        {
            case 1:
                Value = CGAL::make_object(Point(1.0, 2.0));
                break;
            case 2:
                Value = CGAL::make_object(Segment(Point(1.0, 2.0), Point(3.0, 4.0)));
                break;
            case 3:
                Value = CGAL::make_object(42);
                break;
            default:
                break;
        }
    }

    ~TrackedObject()
    {
        ++containerDestroyCount;
    }

    CGAL::Object Value;
};

NativeResult Project(const Point& point) noexcept
{
    ++alternativeTransferCount;
    return {1, CGAL::to_double(point.x()), CGAL::to_double(point.y()), 0.0, 0.0};
}

NativeResult Project(const Segment& segment) noexcept
{
    ++alternativeTransferCount;
    return {
        2,
        CGAL::to_double(segment.source().x()),
        CGAL::to_double(segment.source().y()),
        CGAL::to_double(segment.target().x()),
        CGAL::to_double(segment.target().y())};
}
}

#define CGAL_RUNTIME_EXPORT extern "C" __declspec(dllexport)

CGAL_RUNTIME_EXPORT void CgalRuntime_ResetCounters() noexcept
{
    diagnosticClearCount = 0;
    containerCreateCount = 0;
    containerDestroyCount = 0;
    alternativeTransferCount = 0;
}

CGAL_RUNTIME_EXPORT int CgalRuntime_GetDiagnosticClearCount() noexcept
{
    return diagnosticClearCount;
}

CGAL_RUNTIME_EXPORT int CgalRuntime_GetContainerCreateCount() noexcept
{
    return containerCreateCount;
}

CGAL_RUNTIME_EXPORT int CgalRuntime_GetContainerDestroyCount() noexcept
{
    return containerDestroyCount;
}

CGAL_RUNTIME_EXPORT int CgalRuntime_GetAlternativeTransferCount() noexcept
{
    return alternativeTransferCount;
}

CGAL_RUNTIME_EXPORT void CgalRuntime_ClearError(NativeError* error) noexcept
{
    if (error == nullptr)
    {
        return;
    }

    ++diagnosticClearCount;
    std::free(error->TypeName);
    std::free(error->Message);
    std::free(error->StackTrace);
    *error = {};
}

CGAL_RUNTIME_EXPORT void CgalRuntime_CreateMalformedError(NativeError* error) noexcept
{
    static constexpr char MalformedUtf8[] = {static_cast<char>(0xC3), '(', '\0'};
    SetError(error, 11, "CGAL::Precondition_exception", MalformedUtf8, "fixture.cpp:42");
}

CGAL_RUNTIME_EXPORT void CgalRuntime_InvokeFailure(int scenario, NativeError* error) noexcept
{
    if (error != nullptr)
    {
        *error = {};
    }

    try
    {
        ThrowSelectedFailure(scenario);
    }
    catch (const CGAL::Error_exception& exception)
    {
        const auto stack = FailureStack(exception);
        SetError(error, 10, "CGAL::Error_exception", exception.what(), stack.c_str());
    }
    catch (const CGAL::Precondition_exception& exception)
    {
        const auto stack = FailureStack(exception);
        SetError(error, 11, "CGAL::Precondition_exception", exception.what(), stack.c_str());
    }
    catch (const CGAL::Postcondition_exception& exception)
    {
        const auto stack = FailureStack(exception);
        SetError(error, 12, "CGAL::Postcondition_exception", exception.what(), stack.c_str());
    }
    catch (const CGAL::Assertion_exception& exception)
    {
        const auto stack = FailureStack(exception);
        SetError(error, 13, "CGAL::Assertion_exception", exception.what(), stack.c_str());
    }
    catch (const CGAL::Test_exception& exception)
    {
        const auto stack = FailureStack(exception);
        SetError(error, 14, "CGAL::Test_exception", exception.what(), stack.c_str());
    }
    catch (const CGAL::Warning_exception& exception)
    {
        const auto stack = FailureStack(exception);
        SetError(error, 15, "CGAL::Warning_exception", exception.what(), stack.c_str());
    }
    catch (const CGAL::Failure_exception& exception)
    {
        const auto stack = FailureStack(exception);
        SetError(error, 16, "CGAL::Failure_exception", exception.what(), stack.c_str());
    }
    catch (const std::invalid_argument& exception)
    {
        SetError(error, 1, "std::invalid_argument", exception.what(), nullptr);
    }
    catch (const std::out_of_range& exception)
    {
        SetError(error, 2, "std::out_of_range", exception.what(), nullptr);
    }
    catch (const std::bad_alloc& exception)
    {
        SetError(error, 6, "std::bad_alloc", exception.what(), nullptr);
    }
    catch (const std::overflow_error& exception)
    {
        SetError(error, 7, "std::overflow_error", exception.what(), nullptr);
    }
    catch (const std::underflow_error& exception)
    {
        SetError(error, 7, "std::underflow_error", exception.what(), nullptr);
    }
    catch (const std::exception& exception)
    {
        SetError(error, 9, "std::exception", exception.what(), nullptr);
    }
    catch (...)
    {
        SetError(error, 255, nullptr, nullptr, nullptr);
    }
}

CGAL_RUNTIME_EXPORT void CgalRuntime_CreateVariantResult(int scenario, NativeResult* result) noexcept
{
    if (result == nullptr)
    {
        return;
    }

    TrackedVariant container(scenario);
    if (scenario == 4)
    {
        *result = {255, 0.0, 0.0, 0.0, 0.0};
    }
    else if (!container.Value)
    {
        *result = {};
    }
    else if (const auto* point = std::get_if<Point>(&*container.Value))
    {
        *result = Project(*point);
    }
    else if (const auto* segment = std::get_if<Segment>(&*container.Value))
    {
        *result = Project(*segment);
    }
    else
    {
        *result = {42, 0.0, 0.0, 0.0, 0.0};
    }
}

CGAL_RUNTIME_EXPORT void CgalRuntime_CreateObjectResult(int scenario, NativeResult* result) noexcept
{
    if (result == nullptr)
    {
        return;
    }

    TrackedObject container(scenario);
    if (scenario == 4)
    {
        *result = {255, 0.0, 0.0, 0.0, 0.0};
    }
    else if (container.Value.empty())
    {
        *result = {};
    }
    else if (const auto* point = CGAL::object_cast<Point>(&container.Value))
    {
        *result = Project(*point);
    }
    else if (const auto* segment = CGAL::object_cast<Segment>(&container.Value))
    {
        *result = Project(*segment);
    }
    else
    {
        *result = {42, 0.0, 0.0, 0.0, 0.0};
    }
}
