#ifndef TED_TOOLKIT_OCCT_V1_TEST_H
#define TED_TOOLKIT_OCCT_V1_TEST_H

#include "ted_toolkit_occt_v1.h"

#define TED_OCCT_V1_TEST_ERROR_ARGUMENT INT32_C(1)
#define TED_OCCT_V1_TEST_ERROR_ARGUMENT_OUT_OF_RANGE INT32_C(2)
#define TED_OCCT_V1_TEST_ERROR_ARITHMETIC INT32_C(3)
#define TED_OCCT_V1_TEST_ERROR_INVALID_OPERATION INT32_C(4)
#define TED_OCCT_V1_TEST_ERROR_NULL_OBJECT INT32_C(5)
#define TED_OCCT_V1_TEST_ERROR_OUT_OF_MEMORY INT32_C(6)
#define TED_OCCT_V1_TEST_ERROR_OVERFLOW INT32_C(7)
#define TED_OCCT_V1_TEST_ERROR_OCCT_FAILURE INT32_C(8)
#define TED_OCCT_V1_TEST_ERROR_STD_EXCEPTION INT32_C(9)
#define TED_OCCT_V1_TEST_ERROR_UNKNOWN INT32_C(10)
#define TED_OCCT_V1_TEST_ERROR_RESERVED INT32_C(11)
#define TED_OCCT_V1_TEST_ERROR_DERIVED_PRECEDENCE INT32_C(12)

#define TED_OCCT_V1_TEST_LAYOUT_ERROR_SIZE INT32_C(1)
#define TED_OCCT_V1_TEST_LAYOUT_ERROR_KIND INT32_C(2)
#define TED_OCCT_V1_TEST_LAYOUT_ERROR_TYPE_NAME INT32_C(3)
#define TED_OCCT_V1_TEST_LAYOUT_ERROR_MESSAGE INT32_C(4)
#define TED_OCCT_V1_TEST_LAYOUT_ERROR_STACK_TRACE INT32_C(5)
#define TED_OCCT_V1_TEST_LAYOUT_PNT2D_SIZE INT32_C(6)
#define TED_OCCT_V1_TEST_LAYOUT_PNT2D_X INT32_C(7)
#define TED_OCCT_V1_TEST_LAYOUT_PNT2D_Y INT32_C(8)
#define TED_OCCT_V1_TEST_LAYOUT_BYTES_VIEW_SIZE INT32_C(9)
#define TED_OCCT_V1_TEST_LAYOUT_BYTES_VIEW_DATA INT32_C(10)
#define TED_OCCT_V1_TEST_LAYOUT_BYTES_VIEW_LENGTH INT32_C(11)
#define TED_OCCT_V1_TEST_LAYOUT_OWNED_BYTES_SIZE INT32_C(12)
#define TED_OCCT_V1_TEST_LAYOUT_OWNED_BYTES_DATA INT32_C(13)
#define TED_OCCT_V1_TEST_LAYOUT_OWNED_BYTES_LENGTH INT32_C(14)

#ifdef __cplusplus
extern "C" {
#endif

TED_OCCT_V1_API void TED_OCCT_V1_CALL ted_occt_v1_test_fail_diagnostic_allocation_after(
    int32_t successful_allocations);
TED_OCCT_V1_API ted_occt_v1_error TED_OCCT_V1_CALL ted_occt_v1_test_error(int32_t scenario);
TED_OCCT_V1_API uint64_t TED_OCCT_V1_CALL ted_occt_v1_test_layout(int32_t query);

#ifdef __cplusplus
}
#endif

#endif
