<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\externals\TedToolkit\props\CodeAnalysis.props"/>
  <Import Project="..\..\..\externals\TedToolkit\props\NugetPackage.props"/>

  <PropertyGroup>
    <Title>Occt.Generator</Title>
    <Description>Generate the occt codes.</Description>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClangSharp" />
    <PackageReference Include="libclang.runtime.win-x64" />
    <PackageReference Include="libClangSharp.runtime.win-x64" />
    <PackageReference Include="ModularPipelines" />
    <None Include="..\..\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.Occt.Analyzer.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" PrivateAssets="All"/>
    <None Include="..\..\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.RoslynHelper.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" PrivateAssets="All"/>
    <None Include="..\..\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\ZString.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" PrivateAssets="All"/>
    <None Include="..\..\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\System.Memory.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" PrivateAssets="All"/>
    <PackageReference Include="TedToolkit.RoslynHelper" />
    <PackageReference Include="ZString" />
  </ItemGroup>

</Project>
