// -----------------------------------------------------------------------
// <copyright file="OcctSemanticProfile.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using TedToolkit.CppBindings.Generator.Semantics;

namespace TedToolkit.CppBindings.Occt.Generator.Services;

/// <summary>
/// Supplies OCCT policy to the provider-neutral semantic engine.
/// </summary>
internal static class OcctSemanticProfile
{
    /// <summary>
    /// Gets the emitter key used for managed source file stems.
    /// </summary>
    internal const string ManagedSourceStem = "managed-source-stem";

    /// <summary>
    /// Gets the emitter key used for native source file stems.
    /// </summary>
    internal const string NativeSourceStem = "native-source-stem";

    /// <summary>
    /// Creates the complete OCCT semantic policy set.
    /// </summary>
    /// <returns>The configured shared engine.</returns>
    internal static BindingSemanticEngine Create()
    {
        return new(
            [new TypeRule(),],
            new LayoutPolicy(),
            new TemplatePolicy(),
            [
                new SourceStemEmitter(ManagedSourceStem, normalizeTypeName: false, maxLength: null),
                new SourceStemEmitter(NativeSourceStem, normalizeTypeName: true, maxLength: 80),
            ]);
    }

    /// <summary>
    /// Creates the finite OCCT syntax and runtime policy consumed by Shared's paired emitters.
    /// </summary>
    /// <param name="cSharpNamespace">The generated managed namespace.</param>
    /// <param name="isInternal">Whether record representations are internal.</param>
    /// <returns>The immutable emission profile.</returns>
    internal static BindingEmissionProfile CreateEmissionProfile(string cSharpNamespace, bool isInternal)
    {
        return new()
        {
            CSharpNamespace = cSharpNamespace,
            IsInternal = isInternal,
            IntrusiveRootInterfaceName = "IStandard_Transient",
            ManagedIntrusiveRootInterface = "global::TedToolkit.CppBindings.Occt.IStandard_Transient",
            ManagedOwningIntrusiveHandle = "global::TedToolkit.CppBindings.Occt.Handle",
            ManagedBorrowedIntrusiveHandle = "global::TedToolkit.CppBindings.Occt.handle",
            ManagedNativeErrorProjection = "global::TedToolkit.CppBindings.Occt.NativeErrorProjection",
            NativeErrorClearExport = "NativeError_Clear",
            NativePreamble = "// <auto-generated />\n#include <new>\n#include <utility>\n"
                + "#include <Standard.hxx>\n#include <Standard_Handle.hxx>\n",
            NativePreambleHeaders = ["Standard.hxx", "Standard_Handle.hxx",],
            NativeErrorPreamble = "#include \"NativeError.h\"\n#include <Standard_Failure.hxx>\n",
            NativeExceptionProjections =
            [
                new("Standard_Failure", 9, "\"Standard_Failure\"", "exception.what()"),
            ],
        };
    }

    private sealed class TypeRule : IBindingTypeRule
    {
        /// <inheritdoc />
        public bool TryResolve(CppTypeDescriptor type, out BindingTypeProjection? projection)
        {
            projection = new(type.NativeName, type.NativeName.ToGeneratedTypeName());
            return true;
        }
    }

    private sealed class LayoutPolicy : IBindingLayoutPolicy
    {
        /// <inheritdoc />
        public BindingAdmission Admit(BindingLayoutDescriptor layout)
        {
            return layout.Alignment is 1 or 2 or 4 or 8
                ? BindingAdmission.Admitted
                : BindingAdmission.Reject(
                    $"Native alignment {layout.Alignment} is not supported by win-x64 sequential storage.");
        }
    }

    private sealed class TemplatePolicy : IBindingTemplatePolicy
    {
        /// <inheritdoc />
        public BindingAdmission Admit(BindingTemplateDescriptor template)
        {
            return template.Arguments.Any(string.IsNullOrWhiteSpace)
                ? BindingAdmission.Reject("Template arguments must have stable native spellings.")
                : BindingAdmission.Admitted;
        }
    }

    private sealed class SourceStemEmitter(
        string name,
        bool normalizeTypeName,
        int? maxLength) : IBindingEmitterPrimitive
    {
        /// <inheritdoc />
        public string Name
        {
            get
            {
                return name;
            }
        }

        /// <inheritdoc />
        public string Emit(string value)
        {
            var generatedName = normalizeTypeName ? value.ToGeneratedTypeName() : value;
            return maxLength is { } length
                ? generatedName.ToGeneratedFileStem(length)
                : generatedName.ToGeneratedFileStem();
        }
    }
}