<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\externals\TedToolkit\props\CodeAnalysis.props"/>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1815;RCS1231</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\core\TedToolkit.Occt.Runtime\TedToolkit.Occt.Runtime.csproj" />
  </ItemGroup>

</Project>
