<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DefineConstants Condition="'$(IncludeManifold)' == 'true'">$(DefineConstants);INCLUDE_MANIFOLD</DefineConstants>
    <DefineConstants Condition="'$(IncludeFcl)' == 'true'">$(DefineConstants);INCLUDE_FCL</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TedToolkit.CppBindings.Cgal.Windows" Version="1.0.0" />
    <PackageReference Include="TedToolkit.CppBindings.Occt.Windows" Version="1.0.0" />
    <PackageReference Condition="'$(IncludeManifold)' == 'true'"
                      Include="TedToolkit.CppBindings.Manifold.Windows" Version="1.0.0" />
    <PackageReference Condition="'$(IncludeFcl)' == 'true'"
                      Include="TedToolkit.CppBindings.Fcl.Windows" Version="1.0.0" />
  </ItemGroup>
</Project>
