<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <PackageVersionUnderTest Condition="'$(PackageVersionUnderTest)' == ''">1.0.0</PackageVersionUnderTest>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="TedToolkit.CppBindings.Fcl.Windows" Version="$(PackageVersionUnderTest)" />
  </ItemGroup>
</Project>
