// -----------------------------------------------------------------------
// <copyright file="NativeApiGenerator.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

namespace TedToolkit.CppBindings.Generator.Generators;

/// <summary>
/// Emits the existing process-lifetime native module loader without provider declaration knowledge.
/// </summary>
internal static class NativeApiGenerator
{
    /// <summary>
    /// The reserved managed loader filename.
    /// </summary>
    internal const string FileName = "NativeApi.g.cs";

    /// <summary>
    /// Generates the process-lifetime native table loader.
    /// </summary>
    /// <param name="options">Validated namespace and artifact settings.</param>
    /// <returns>The generated managed source.</returns>
    internal static string Generate(GenerationOptions options)
    {
        return $$"""
                 // <auto-generated />
                 #pragma warning disable

                 using System.Runtime.InteropServices;

                 namespace {{options.CSharpNamespace}};

                 internal static unsafe class NativeApi
                 {
                     private static readonly nint Module = NativeLibrary.Load(
                         "{{options.NativeLibraryBaseName}}", typeof(NativeApi).Assembly, null);
                     private static readonly nint* Functions = ((delegate* unmanaged[Cdecl]<nint*>)NativeLibrary.GetExport(
                         Module, "NativeApi_GetFunctionTable"))();

                     internal static nint GetFunction(int index) => Functions[index];
                 }

                 """;
    }
}