<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\externals\TedToolkit\props\CodeAnalysis.props"/>

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);ConsoleUse</NoWarn>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Analyzer Include="..\..\src\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.Occt.Analyzer.dll"/>
    <Analyzer Include="..\..\src\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.RoslynHelper.dll"/>
    <Analyzer Include="..\..\src\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\ZString.dll"/>
    <Analyzer Include="..\..\src\tools\TedToolkit.Occt.Analyzer\bin\$(Configuration)\netstandard2.0\System.Memory.dll"/>
    <ProjectReference Include="..\..\src\core\TedToolkit.Occt.Generator\TedToolkit.Occt.Generator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="libclang.runtime.linux-x64" />
    <PackageReference Include="libClangSharp.runtime.linux-x64" />
    <PackageReference Include="Sourcy.DotNet">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
