// -----------------------------------------------------------------------
// <copyright file="CgalSourceRenderer.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

namespace TedToolkit.CppBindings.Cgal.Generator;

/// <summary>
/// Renders the finite managed API, native adapter, and native build description.
/// </summary>
internal static class CgalSourceRenderer
{
    /// <summary>
    /// Renders the managed API against the exact sorted function-table slots.
    /// </summary>
    /// <param name="cSharpNamespace">The generated namespace.</param>
    /// <param name="exports">The exact sorted native export inventory.</param>
    /// <returns>The complete managed source.</returns>
    internal static string RenderManaged(string cSharpNamespace, IReadOnlyList<string> exports)
    {
        var slots = exports.Select(static (name, index) => (name, index))
            .ToDictionary(static item => item.name, static item => item.index, StringComparer.Ordinal);
        return $$"""
                 // <auto-generated />
                 #pragma warning disable

                 using System.Runtime.InteropServices;
                 using TedToolkit.CppBindings;

                 namespace {{cSharpNamespace}};

                 [StructLayout(LayoutKind.Sequential)]
                 public readonly struct Point_2(double x, double y)
                 {
                     public double X { get; } = x;
                     public double Y { get; } = y;

                     public double Cartesian(int index) => CgalKernel.Cartesian(this, index);
                 }

                 [StructLayout(LayoutKind.Sequential)]
                 public readonly struct Point_3(double x, double y, double z)
                 {
                     public double X { get; } = x;
                     public double Y { get; } = y;
                     public double Z { get; } = z;

                     public double Cartesian(int index) => CgalKernel.Cartesian(this, index);
                 }

                 [StructLayout(LayoutKind.Sequential)]
                 public readonly struct Segment_2(Point_2 source, Point_2 target)
                 {
                     public Point_2 Source { get; } = source;
                     public Point_2 Target { get; } = target;

                     public double SquaredLength => CgalKernel.SquaredLength(this);
                 }

                 public enum Segment_2IntersectionKind
                 {
                     None = 0,
                     Point = 1,
                     Segment = 2,
                 }

                 public readonly struct Segment_2Intersection
                 {
                     private readonly Point_2 _point;
                     private readonly Segment_2 _segment;

                     private Segment_2Intersection(
                         Segment_2IntersectionKind kind,
                         Point_2 point,
                         Segment_2 segment)
                     {
                         Kind = kind;
                         _point = point;
                         _segment = segment;
                     }

                     public Segment_2IntersectionKind Kind { get; }

                     public bool TryGetPoint(out Point_2 value)
                     {
                         value = _point;
                         return Kind == Segment_2IntersectionKind.Point;
                     }

                     public bool TryGetSegment(out Segment_2 value)
                     {
                         value = _segment;
                         return Kind == Segment_2IntersectionKind.Segment;
                     }

                     internal static Segment_2Intersection FromNative(
                         int tag,
                         double ax,
                         double ay,
                         double bx,
                         double by)
                     {
                         return tag switch
                         {
                             0 => new(Segment_2IntersectionKind.None, default, default),
                             1 => new(Segment_2IntersectionKind.Point, new(ax, ay), default),
                             2 => new(Segment_2IntersectionKind.Segment, default, new(new(ax, ay), new(bx, by))),
                             _ => throw new CgalUnknownResultException(
                                 $"Native CGAL intersection returned undeclared alternative tag {tag}."),
                         };
                     }
                 }

                 public static unsafe class CgalKernel
                 {
                     public static double SquaredDistance(Point_2 left, Point_2 right)
                     {
                         NativeError error = default;
                         var result = ((delegate* unmanaged[Cdecl]<double, double, double, double, NativeError*, double>)
                             NativeApi.GetFunction({{slots["Cgal_Point2_SquaredDistance"]}}))(
                                 left.X, left.Y, right.X, right.Y, &error);
                         ThrowIfFailed(ref error);
                         return result;
                     }

                     public static double SquaredDistance(Point_3 left, Point_3 right)
                     {
                         NativeError error = default;
                         var result = ((delegate* unmanaged[Cdecl]<double, double, double, double, double, double, NativeError*, double>)
                             NativeApi.GetFunction({{slots["Cgal_Point3_SquaredDistance"]}}))(
                                 left.X, left.Y, left.Z, right.X, right.Y, right.Z, &error);
                         ThrowIfFailed(ref error);
                         return result;
                     }

                     public static Segment_2Intersection Intersect(Segment_2 left, Segment_2 right)
                     {
                         NativeError error = default;
                         double ax = 0;
                         double ay = 0;
                         double bx = 0;
                         double by = 0;
                         var tag = ((delegate* unmanaged[Cdecl]<
                             double, double, double, double,
                             double, double, double, double,
                             double*, double*, double*, double*, NativeError*, int>)
                             NativeApi.GetFunction({{slots["Cgal_Segment2_Intersection"]}}))(
                                 left.Source.X, left.Source.Y, left.Target.X, left.Target.Y,
                                 right.Source.X, right.Source.Y, right.Target.X, right.Target.Y,
                                 &ax, &ay, &bx, &by, &error);
                         ThrowIfFailed(ref error);
                         return Segment_2Intersection.FromNative(tag, ax, ay, bx, by);
                     }

                     internal static double Cartesian(Point_2 point, int index)
                     {
                         NativeError error = default;
                         var result = ((delegate* unmanaged[Cdecl]<double, double, int, NativeError*, double>)
                             NativeApi.GetFunction({{slots["Cgal_Point2_Cartesian"]}}))(
                                 point.X, point.Y, index, &error);
                         ThrowIfFailed(ref error);
                         return result;
                     }

                     internal static double Cartesian(Point_3 point, int index)
                     {
                         NativeError error = default;
                         var result = ((delegate* unmanaged[Cdecl]<double, double, double, int, NativeError*, double>)
                             NativeApi.GetFunction({{slots["Cgal_Point3_Cartesian"]}}))(
                                 point.X, point.Y, point.Z, index, &error);
                         ThrowIfFailed(ref error);
                         return result;
                     }

                     internal static double SquaredLength(Segment_2 segment)
                     {
                         NativeError error = default;
                         var result = ((delegate* unmanaged[Cdecl]<double, double, double, double, NativeError*, double>)
                             NativeApi.GetFunction({{slots["Cgal_Segment2_SquaredLength"]}}))(
                                 segment.Source.X, segment.Source.Y,
                                 segment.Target.X, segment.Target.Y,
                                 &error);
                         ThrowIfFailed(ref error);
                         return result;
                     }

                     private static void ThrowIfFailed(ref NativeError error)
                     {
                         NativeErrorProjection.ThrowIfFailed(
                             ref error,
                             (delegate* unmanaged[Cdecl]<NativeError*, void>)
                                 NativeApi.GetFunction({{slots["Cgal_NativeError_Clear"]}}));
                     }
                 }

                 """;
    }

    /// <summary>
    /// Renders the native CGAL adapter and error boundary.
    /// </summary>
    /// <returns>The complete native source.</returns>
    internal static string RenderNative()
    {
        return """
               // <auto-generated />
               #include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
               #include <CGAL/Object.h>
               #include <CGAL/assertions.h>
               #include <CGAL/exceptions.h>
               #include <CGAL/intersections.h>
               #include <CGAL/squared_distance_2.h>
               #include <CGAL/squared_distance_3.h>
               #include <cstdlib>
               #include <cstring>
               #include <exception>
               #include <new>
               #include <stdexcept>
               #include <string>
               #include <variant>

               using Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
               using Point2 = Kernel::Point_2;
               using Point3 = Kernel::Point_3;
               using Segment2 = Kernel::Segment_2;

               struct NativeError
               {
                   int Kind;
                   char* TypeName;
                   char* Message;
                   char* StackTrace;
               };

               static char* CopyText(const char* text) noexcept
               {
                   if (text == nullptr) return nullptr;
                   const auto length = std::strlen(text) + 1;
                   auto* copy = static_cast<char*>(std::malloc(length));
                   if (copy != nullptr) std::memcpy(copy, text, length);
                   return copy;
               }

               static void SetError(NativeError* error, int kind, const char* type, const char* message, const char* stack) noexcept
               {
                   if (error == nullptr) return;
                   error->Kind = kind;
                   error->TypeName = CopyText(type);
                   error->Message = CopyText(message);
                   error->StackTrace = CopyText(stack);
               }

               static std::string FailureStack(const CGAL::Failure_exception& failure)
               {
                   return failure.filename() + ":" + std::to_string(failure.line_number());
               }

               static void ProjectFailure(NativeError* error) noexcept
               {
                   try { throw; }
                   catch (const CGAL::Error_exception& exception) { auto stack = FailureStack(exception); SetError(error, 10, "CGAL::Error_exception", exception.what(), stack.c_str()); }
                   catch (const CGAL::Precondition_exception& exception) { auto stack = FailureStack(exception); SetError(error, 11, "CGAL::Precondition_exception", exception.what(), stack.c_str()); }
                   catch (const CGAL::Postcondition_exception& exception) { auto stack = FailureStack(exception); SetError(error, 12, "CGAL::Postcondition_exception", exception.what(), stack.c_str()); }
                   catch (const CGAL::Assertion_exception& exception) { auto stack = FailureStack(exception); SetError(error, 13, "CGAL::Assertion_exception", exception.what(), stack.c_str()); }
                   catch (const CGAL::Test_exception& exception) { auto stack = FailureStack(exception); SetError(error, 14, "CGAL::Test_exception", exception.what(), stack.c_str()); }
                   catch (const CGAL::Warning_exception& exception) { auto stack = FailureStack(exception); SetError(error, 15, "CGAL::Warning_exception", exception.what(), stack.c_str()); }
                   catch (const CGAL::Failure_exception& exception) { auto stack = FailureStack(exception); SetError(error, 16, "CGAL::Failure_exception", exception.what(), stack.c_str()); }
                   catch (const std::invalid_argument& exception) { SetError(error, 1, "std::invalid_argument", exception.what(), ""); }
                   catch (const std::out_of_range& exception) { SetError(error, 2, "std::out_of_range", exception.what(), ""); }
                   catch (const std::bad_alloc& exception) { SetError(error, 6, "std::bad_alloc", exception.what(), ""); }
                   catch (const std::overflow_error& exception) { SetError(error, 7, "std::overflow_error", exception.what(), ""); }
                   catch (const std::underflow_error& exception) { SetError(error, 7, "std::underflow_error", exception.what(), ""); }
                   catch (const std::exception& exception) { SetError(error, 9, "std::exception", exception.what(), ""); }
                   catch (...) { SetError(error, 255, "unknown", "Unknown native CGAL failure.", ""); }
               }

               extern "C" void Cgal_NativeError_Clear(NativeError* error) noexcept
               {
                   if (error == nullptr) return;
                   std::free(error->TypeName);
                   std::free(error->Message);
                   std::free(error->StackTrace);
                   *error = {};
               }

               extern "C" double Cgal_Point2_Cartesian(double x, double y, int index, NativeError* error) noexcept
               {
                   try { CGAL_precondition(index >= 0 && index < 2); return Point2(x, y).cartesian(index); }
                   catch (...) { ProjectFailure(error); return 0.0; }
               }

               extern "C" double Cgal_Point3_Cartesian(double x, double y, double z, int index, NativeError* error) noexcept
               {
                   try { CGAL_precondition(index >= 0 && index < 3); return Point3(x, y, z).cartesian(index); }
                   catch (...) { ProjectFailure(error); return 0.0; }
               }

               extern "C" double Cgal_Point2_SquaredDistance(
                   double ax, double ay, double bx, double by, NativeError* error) noexcept
               {
                   try { return CGAL::to_double(CGAL::squared_distance(Point2(ax, ay), Point2(bx, by))); }
                   catch (...) { ProjectFailure(error); return 0.0; }
               }

               extern "C" double Cgal_Point3_SquaredDistance(
                   double ax, double ay, double az, double bx, double by, double bz, NativeError* error) noexcept
               {
                   try { return CGAL::to_double(CGAL::squared_distance(Point3(ax, ay, az), Point3(bx, by, bz))); }
                   catch (...) { ProjectFailure(error); return 0.0; }
               }

               extern "C" double Cgal_Segment2_SquaredLength(
                   double ax, double ay, double bx, double by, NativeError* error) noexcept
               {
                   try { return CGAL::to_double(Segment2(Point2(ax, ay), Point2(bx, by)).squared_length()); }
                   catch (...) { ProjectFailure(error); return 0.0; }
               }

               extern "C" int Cgal_Segment2_Intersection(
                   double a0x, double a0y, double a1x, double a1y,
                   double b0x, double b0y, double b1x, double b1y,
                   double* ax, double* ay, double* bx, double* by, NativeError* error) noexcept
               {
                   try
                   {
                       auto result = CGAL::intersection(
                           Segment2(Point2(a0x, a0y), Point2(a1x, a1y)),
                           Segment2(Point2(b0x, b0y), Point2(b1x, b1y)));
                       if (!result) return 0;
                       if (const auto* point = std::get_if<Point2>(&*result))
                       {
                           *ax = CGAL::to_double(point->x());
                           *ay = CGAL::to_double(point->y());
                           return 1;
                       }
                       if (const auto* segment = std::get_if<Segment2>(&*result))
                       {
                           *ax = CGAL::to_double(segment->source().x());
                           *ay = CGAL::to_double(segment->source().y());
                           *bx = CGAL::to_double(segment->target().x());
                           *by = CGAL::to_double(segment->target().y());
                           return 2;
                       }
                       return 255;
                   }
                   catch (...) { ProjectFailure(error); return 0; }
               }

               """;
    }

    /// <summary>
    /// Renders the native CMake project for the exact source inventory.
    /// </summary>
    /// <param name="nativeLibraryBaseName">The package-owned native library basename.</param>
    /// <param name="sources">The complete compiled native sources.</param>
    /// <returns>The CMake project text.</returns>
    internal static string RenderCMake(string nativeLibraryBaseName, IReadOnlyList<string> sources)
    {
        var sourceList = string.Join("\n", sources.Order(StringComparer.Ordinal).Select(static source => "    " + source));
        return $$"""
                 cmake_minimum_required(VERSION 3.28)
                 project(TedToolkitCppBindingsCgal LANGUAGES CXX)

                 find_package(CGAL CONFIG REQUIRED)

                 add_library({{nativeLibraryBaseName}} SHARED
                 {{sourceList}}
                 )
                 target_compile_features({{nativeLibraryBaseName}} PRIVATE cxx_std_20)
                 target_compile_definitions({{nativeLibraryBaseName}} PRIVATE CGAL_DEBUG)
                 target_link_libraries({{nativeLibraryBaseName}} PRIVATE CGAL::CGAL)

                 """;
    }
}