// -----------------------------------------------------------------------
// <copyright file="CgalSourceRenderer.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

namespace TedToolkit.CppBindings.Cgal.Generator;

/// <summary>
/// Renders provider support around declarations emitted by the Shared semantic engine.
/// </summary>
internal static class CgalSourceRenderer
{
    /// <summary>
    /// Renders the provider adapter types whose declarations are projected by Shared.
    /// </summary>
    /// <param name="profile">The selected finite profile.</param>
    /// <returns>The native adapter header.</returns>
    internal static string RenderAdapter(CgalProfileManifest profile)
    {
        return $$"""
                 // <auto-generated />
                 #pragma once

                 #include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
                 #include <CGAL/assertions.h>
                 #include <CGAL/intersections.h>
                 #include <CGAL/squared_distance_2.h>
                 #include <CGAL/squared_distance_3.h>
                 #include <variant>

                 namespace TedToolkit::CppBindings::Cgal
                 {
                     using NativeKernel = {{profile.KernelAlias}};
                     using NativePoint2 = NativeKernel::Point_2;
                     using NativePoint3 = NativeKernel::Point_3;
                     using NativeSegment2 = NativeKernel::Segment_2;

                     struct Point_2
                     {
                         double X;
                         double Y;

                         Point_2(double x, double y) noexcept : X(x), Y(y) {}

                         double Cartesian(int index) const
                         {
                             CGAL_precondition(index >= 0 && index < 2);
                             return NativePoint2(X, Y).cartesian(index);
                         }
                     };

                     struct Point_3
                     {
                         double X;
                         double Y;
                         double Z;

                         Point_3(double x, double y, double z) noexcept : X(x), Y(y), Z(z) {}

                         double Cartesian(int index) const
                         {
                             CGAL_precondition(index >= 0 && index < 3);
                             return NativePoint3(X, Y, Z).cartesian(index);
                         }
                     };

                     struct Segment_2
                     {
                         Point_2 SourceValue;
                         Point_2 TargetValue;

                         Segment_2(Point_2 source, Point_2 target) noexcept
                             : SourceValue(source), TargetValue(target) {}

                         Point_2 Source() const { return SourceValue; }
                         Point_2 Target() const { return TargetValue; }

                         double SquaredLength() const
                         {
                             return CGAL::to_double(NativeSegment2(
                                 NativePoint2(SourceValue.X, SourceValue.Y),
                                 NativePoint2(TargetValue.X, TargetValue.Y)).squared_length());
                         }
                     };

                     struct Segment_2_Intersection_Transport
                     {
                         int Tag{};
                         double AX{};
                         double AY{};
                         double BX{};
                         double BY{};
                     };

                     struct Kernel_API
                     {
                         static double SquaredDistance(Point_2 left, Point_2 right)
                         {
                             return CGAL::to_double(CGAL::squared_distance(
                                 NativePoint2(left.X, left.Y), NativePoint2(right.X, right.Y)));
                         }

                         static double SquaredDistance(Point_3 left, Point_3 right)
                         {
                             return CGAL::to_double(CGAL::squared_distance(
                                 NativePoint3(left.X, left.Y, left.Z),
                                 NativePoint3(right.X, right.Y, right.Z)));
                         }

                         static Segment_2_Intersection_Transport Intersect(Segment_2 left, Segment_2 right)
                         {
                             const auto first = NativeSegment2(
                                 NativePoint2(left.SourceValue.X, left.SourceValue.Y),
                                 NativePoint2(left.TargetValue.X, left.TargetValue.Y));
                             const auto second = NativeSegment2(
                                 NativePoint2(right.SourceValue.X, right.SourceValue.Y),
                                 NativePoint2(right.TargetValue.X, right.TargetValue.Y));
                             const auto result = CGAL::intersection(first, second);
                             if (!result) return {};
                             if (const auto* point = std::get_if<NativePoint2>(&*result))
                             {
                                 return {1, CGAL::to_double(point->x()), CGAL::to_double(point->y()), 0, 0};
                             }

                             if (const auto* segment = std::get_if<NativeSegment2>(&*result))
                             {
                                 return {
                                     2,
                                     CGAL::to_double(segment->source().x()),
                                     CGAL::to_double(segment->source().y()),
                                     CGAL::to_double(segment->target().x()),
                                     CGAL::to_double(segment->target().y())};
                             }

                             return {255, 0, 0, 0, 0};
                         }
                     };
                 }
                 """;
    }

    /// <summary>
    /// Renders the operation-specific discriminated intersection result facade.
    /// </summary>
    /// <param name="cSharpNamespace">The generated namespace.</param>
    /// <returns>The managed result projection.</returns>
    internal static string RenderManagedResultProjection(string cSharpNamespace)
    {
        return $$"""
                 // <auto-generated />
                 #pragma warning disable

                 namespace {{cSharpNamespace}};

                 public enum Segment_2IntersectionKind
                 {
                     None = 0,
                     Point = 1,
                     Segment = 2,
                 }

                 public readonly struct Segment_2Intersection
                 {
                     private readonly Point_2 _point;
                     private readonly Segment_2 _segment;

                     private Segment_2Intersection(
                         Segment_2IntersectionKind kind,
                         Point_2 point,
                         Segment_2 segment)
                     {
                         Kind = kind;
                         _point = point;
                         _segment = segment;
                     }

                     public Segment_2IntersectionKind Kind { get; }

                     public bool TryGetPoint(out Point_2 value)
                     {
                         value = _point;
                         return Kind == Segment_2IntersectionKind.Point;
                     }

                     public bool TryGetSegment(out Segment_2 value)
                     {
                         value = _segment;
                         return Kind == Segment_2IntersectionKind.Segment;
                     }

                     internal static Segment_2Intersection FromNative(Segment_2_Intersection_Transport value)
                     {
                         return value.Tag switch
                         {
                             0 => new(Segment_2IntersectionKind.None, default, default),
                             1 => new(Segment_2IntersectionKind.Point, new() { X = value.AX, Y = value.AY }, default),
                             2 => new(
                                 Segment_2IntersectionKind.Segment,
                                 default,
                                 new()
                                 {
                                     Source = new() { X = value.AX, Y = value.AY },
                                     Target = new() { X = value.BX, Y = value.BY },
                                 }),
                             _ => throw new CgalUnknownResultException(
                                 $"Native CGAL intersection returned undeclared alternative tag {value.Tag}."),
                         };
                     }
                 }

                 public static class CgalKernel
                 {
                     public static double SquaredDistance(Point_2 left, Point_2 right)
                         => Kernel_APIExtensions.SquaredDistance(left, right);

                     public static double SquaredDistance(Point_3 left, Point_3 right)
                         => Kernel_APIExtensions.SquaredDistance(left, right);

                     public static Segment_2Intersection Intersect(Segment_2 left, Segment_2 right)
                         => Segment_2Intersection.FromNative(Kernel_APIExtensions.Intersect(left, right));
                 }
                 """;
    }

    /// <summary>
    /// Renders the native diagnostic carrier declarations.
    /// </summary>
    /// <returns>The native diagnostic header.</returns>
    internal static string RenderNativeErrorHeader()
    {
        return """
               // <auto-generated />
               #pragma once

               #include <CGAL/exceptions.h>
               #include <string>

               struct NativeError
               {
                   int Kind;
                   char* TypeName;
                   char* Message;
                   char* StackTrace;
               };

               inline std::string CgalFailureStack(const CGAL::Failure_exception& failure)
               {
                   return failure.filename() + ":" + std::to_string(failure.line_number());
               }

               extern "C" void Cgal_NativeError_Clear(NativeError* error) noexcept;
               extern "C" void Cgal_NativeError_Set(
                   NativeError* error,
                   int kind,
                   const char* typeName,
                   const char* message,
                   const char* stackTrace) noexcept;
               """;
    }

    /// <summary>
    /// Renders the exact-once native diagnostic implementation.
    /// </summary>
    /// <returns>The native diagnostic implementation.</returns>
    internal static string RenderNativeErrorSource()
    {
        return """
               // <auto-generated />
               #include "CgalNativeError.hpp"

               #include <cstdlib>
               #include <cstring>

               static char* CgalCopyText(const char* value) noexcept
               {
                   if (value == nullptr) return nullptr;
                   const auto length = std::strlen(value) + 1;
                   auto* copy = static_cast<char*>(std::malloc(length));
                   if (copy != nullptr) std::memcpy(copy, value, length);
                   return copy;
               }

               extern "C" void Cgal_NativeError_Clear(NativeError* error) noexcept
               {
                   if (error == nullptr) return;
                   std::free(error->TypeName);
                   std::free(error->Message);
                   std::free(error->StackTrace);
                   *error = {};
               }

               extern "C" void Cgal_NativeError_Set(
                   NativeError* error,
                   int kind,
                   const char* typeName,
                   const char* message,
                   const char* stackTrace) noexcept
               {
                   if (error == nullptr) return;
                   error->Kind = kind;
                   error->TypeName = CgalCopyText(typeName);
                   error->Message = CgalCopyText(message);
                   error->StackTrace = CgalCopyText(stackTrace);
               }
               """;
    }

    /// <summary>
    /// Renders the native project for the Shared-emitted and provider support sources.
    /// </summary>
    /// <param name="nativeLibraryBaseName">The native library basename.</param>
    /// <param name="sources">The exact compiled source inventory.</param>
    /// <returns>The CMake project.</returns>
    internal static string RenderCMake(string nativeLibraryBaseName, IReadOnlyList<string> sources)
    {
        var sourceList = string.Join("\n", sources.Order(StringComparer.Ordinal).Select(static source => "    " + source));
        return $$"""
                 cmake_minimum_required(VERSION 3.28)
                 project(TedToolkitCppBindingsCgal LANGUAGES CXX)

                 find_package(CGAL CONFIG REQUIRED)

                 add_library({{nativeLibraryBaseName}} SHARED
                 {{sourceList}}
                 )
                 target_compile_features({{nativeLibraryBaseName}} PRIVATE cxx_std_20)
                 target_compile_definitions({{nativeLibraryBaseName}} PRIVATE CGAL_DEBUG)
                 target_include_directories({{nativeLibraryBaseName}} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
                 target_link_libraries({{nativeLibraryBaseName}} PRIVATE CGAL::CGAL)
                 """;
    }
}