// -----------------------------------------------------------------------
// <copyright file="CgalSourceRenderer.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using TedToolkit.RoslynHelper.Generators;
using TedToolkit.RoslynHelper.Generators.Syntaxes;

using static TedToolkit.RoslynHelper.Generators.SourceComposer;

namespace TedToolkit.CppBindings.Cgal.Generator;

/// <summary>
/// Renders provider support around declarations emitted by the Shared semantic engine.
/// </summary>
internal static class CgalSourceRenderer
{
    /// <summary>
    /// Renders the provider adapter types whose declarations are projected by Shared.
    /// </summary>
    /// <param name="profile">The selected finite profile.</param>
    /// <returns>The native adapter header.</returns>
    internal static string RenderAdapter(CgalProfileManifest profile)
    {
        return $$"""
                 // <auto-generated />
                 #pragma once

                 #include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
                 #include <CGAL/assertions.h>
                 #include <CGAL/intersections.h>
                 #include <CGAL/squared_distance_2.h>
                 #include <CGAL/squared_distance_3.h>
                 #include <variant>

                 namespace TedToolkit::CppBindings::Cgal
                 {
                     using NativeKernel = {{profile.KernelAlias}};
                     using NativePoint2 = NativeKernel::Point_2;
                     using NativePoint3 = NativeKernel::Point_3;
                     using NativeSegment2 = NativeKernel::Segment_2;

                     struct Point_2
                     {
                         double StorageX;
                         double StorageY;

                         Point_2(double x, double y) noexcept : StorageX(x), StorageY(y) {}

                         const double& X() const noexcept { return StorageX; }
                         const double& Y() const noexcept { return StorageY; }

                         double Cartesian(int index) const
                         {
                             CGAL_precondition(index >= 0 && index < 2);
                             return NativePoint2(StorageX, StorageY).cartesian(index);
                         }
                     };

                     struct Point_3
                     {
                         double StorageX;
                         double StorageY;
                         double StorageZ;

                         Point_3(double x, double y, double z) noexcept
                             : StorageX(x), StorageY(y), StorageZ(z) {}

                         const double& X() const noexcept { return StorageX; }
                         const double& Y() const noexcept { return StorageY; }
                         const double& Z() const noexcept { return StorageZ; }

                         double Cartesian(int index) const
                         {
                             CGAL_precondition(index >= 0 && index < 3);
                             return NativePoint3(StorageX, StorageY, StorageZ).cartesian(index);
                         }
                     };

                     struct Segment_2
                     {
                         Point_2 StorageSource;
                         Point_2 StorageTarget;

                         Segment_2(Point_2 source, Point_2 target) noexcept
                             : StorageSource(source), StorageTarget(target) {}

                         const Point_2& Source() const noexcept { return StorageSource; }
                         const Point_2& Target() const noexcept { return StorageTarget; }

                         double SquaredLength() const
                         {
                             return CGAL::to_double(NativeSegment2(
                                 NativePoint2(StorageSource.StorageX, StorageSource.StorageY),
                                 NativePoint2(StorageTarget.StorageX, StorageTarget.StorageY)).squared_length());
                         }
                     };

                     struct Segment_2_Intersection_Transport
                     {
                         int StorageTag{};
                         double StorageAX{};
                         double StorageAY{};
                         double StorageBX{};
                         double StorageBY{};
                     };

                     struct Kernel_API
                     {
                         static double SquaredDistance(Point_2 left, Point_2 right)
                         {
                             return CGAL::to_double(CGAL::squared_distance(
                                 NativePoint2(left.StorageX, left.StorageY),
                                 NativePoint2(right.StorageX, right.StorageY)));
                         }

                         static double SquaredDistance(Point_3 left, Point_3 right)
                         {
                             return CGAL::to_double(CGAL::squared_distance(
                                 NativePoint3(left.StorageX, left.StorageY, left.StorageZ),
                                 NativePoint3(right.StorageX, right.StorageY, right.StorageZ)));
                         }

                         static Segment_2_Intersection_Transport Intersect(Segment_2 left, Segment_2 right)
                         {
                             const auto first = NativeSegment2(
                                 NativePoint2(left.StorageSource.StorageX, left.StorageSource.StorageY),
                                 NativePoint2(left.StorageTarget.StorageX, left.StorageTarget.StorageY));
                             const auto second = NativeSegment2(
                                 NativePoint2(right.StorageSource.StorageX, right.StorageSource.StorageY),
                                 NativePoint2(right.StorageTarget.StorageX, right.StorageTarget.StorageY));
                             const auto result = CGAL::intersection(first, second);
                             if (!result) return {};
                             if (const auto* point = std::get_if<NativePoint2>(&*result))
                             {
                                 return {1, CGAL::to_double(point->x()), CGAL::to_double(point->y()), 0, 0};
                             }

                             if (const auto* segment = std::get_if<NativeSegment2>(&*result))
                             {
                                 return {
                                     2,
                                     CGAL::to_double(segment->source().x()),
                                     CGAL::to_double(segment->source().y()),
                                     CGAL::to_double(segment->target().x()),
                                     CGAL::to_double(segment->target().y())};
                             }

                             return {255, 0, 0, 0, 0};
                         }
                     };
                 }
                 """;
    }

    /// <summary>
    /// Renders the operation-specific discriminated intersection result facade.
    /// </summary>
    /// <param name="cSharpNamespace">The generated namespace.</param>
    /// <returns>The managed result projection.</returns>
    internal static string RenderManagedResultProjection(string cSharpNamespace)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(cSharpNamespace);
        var kind = new TedToolkit.RoslynHelper.Generators.Syntaxes.Enum(
                "Segment_2IntersectionKind",
                DataType.Int).Public
            .AddEnumMember(new EnumMember("None", 0.ToLiteral()))
            .AddEnumMember(new EnumMember("Point", 1.ToLiteral()))
            .AddEnumMember(new EnumMember("Segment", 2.ToLiteral()));

        var result = new TypeDeclaration("Segment_2Intersection", TypeDeclarationType.STRUCT).Public.Readonly
            .AddMember(new Field(new DataType("Point_2"), "_point").Private.Readonly)
            .AddMember(new Field(new DataType("Segment_2"), "_segment").Private.Readonly)
            .AddMember(CreateIntersectionConstructor())
            .AddMember(AutoProperty("Segment_2IntersectionKind", "Kind"))
            .AddMember(CreateTryGet("Point", "Point_2", "_point"))
            .AddMember(CreateTryGet("Segment", "Segment_2", "_segment"))
            .AddMember(CreateFromNative());

        var kernel = new TypeDeclaration("CgalKernel", TypeDeclarationType.CLASS).Public.Static
            .AddMember(CreateKernelMethod(
                "SquaredDistance",
                "double",
                "Point_2",
                "Kernel_APIExtensions.SquaredDistance(left, right)"))
            .AddMember(CreateKernelMethod(
                "SquaredDistance",
                "double",
                "Point_3",
                "Kernel_APIExtensions.SquaredDistance(left, right)"))
            .AddMember(CreateKernelMethod(
                "Intersect",
                "Segment_2Intersection",
                "Segment_2",
                "Segment_2Intersection.FromNative(Kernel_APIExtensions.Intersect(left, right))"));

        return File()
            .AddNameSpace(NameSpace(cSharpNamespace)
                .AddMember(kind)
                .AddMember(result)
                .AddMember(kernel))
            .ToCode();
    }

    private static Constructor CreateIntersectionConstructor()
    {
        var constructor = new Constructor();
        constructor.Owner = "Segment_2Intersection";
        constructor.Accessibility = Accessibility.PRIVATE;
        constructor.AddParameter(Parameter(new DataType("Segment_2IntersectionKind"), "kind"));
        constructor.AddParameter(Parameter(new DataType("Point_2"), "point"));
        constructor.AddParameter(Parameter(new DataType("Segment_2"), "segment"));
        constructor.AddStatement(new Custom("Kind = kind;"));
        constructor.AddStatement(new Custom("_point = point;"));
        constructor.AddStatement(new Custom("_segment = segment;"));
        return constructor;
    }

    private static Property AutoProperty(string type, string name)
    {
        return new Property(new DataType(type), name).Public
            .AddAccessor(new Accessor(AccessorType.GET));
    }

    private static Method CreateTryGet(string kind, string type, string storage)
    {
        return new Method("TryGet" + kind, ReturnType(DataType.Bool)).Public
            .AddParameter(Parameter(new DataType(type).Out, "value"))
            .AddStatement(new Custom("value = " + storage + ";"))
            .AddStatement(new CustomExpression("Kind == Segment_2IntersectionKind." + kind).Return);
    }

    private static Method CreateFromNative()
    {
        const string switchExpression = "value.Tag switch\n"
                                        + "{\n"
                                        + "    0 => new(Segment_2IntersectionKind.None, default, default),\n"
                                        + "    1 => new(\n"
                                        + "        Segment_2IntersectionKind.Point,\n"
                                        + "        Point_2Extensions.Create(value.AX, value.AY),\n"
                                        + "        default),\n"
                                        + "    2 => new(\n"
                                        + "        Segment_2IntersectionKind.Segment,\n"
                                        + "        default,\n"
                                        + "        Segment_2Extensions.Create(\n"
                                        + "            Point_2Extensions.Create(value.AX, value.AY),\n"
                                        + "            Point_2Extensions.Create(value.BX, value.BY))),\n"
                                        + "    _ => throw new CgalUnknownResultException(\n"
                                        + "        $\"Native CGAL intersection returned undeclared alternative tag {value.Tag}.\"),\n"
                                        + "}";
        return new Method("FromNative", ReturnType(new DataType("Segment_2Intersection"))).Internal.Static
            .AddParameter(Parameter(new DataType("Segment_2_Intersection_Transport"), "value"))
            .AddStatement(new CustomExpression(switchExpression).Return);
    }

    private static Method CreateKernelMethod(
        string name,
        string returnType,
        string parameterType,
        string expression)
    {
        return new Method(name, ReturnType(new DataType(returnType))).Public.Static
            .AddParameter(Parameter(new DataType(parameterType), "left"))
            .AddParameter(Parameter(new DataType(parameterType), "right"))
            .AddStatement(new CustomExpression(expression).Return);
    }

    /// <summary>
    /// Renders the CGAL-specific includes and stack helper consumed by Shared diagnostic emission.
    /// </summary>
    /// <returns>The provider-specific native diagnostic preamble.</returns>
    internal static string RenderNativeErrorPreamble()
    {
        return """
               #include <CGAL/exceptions.h>
               #include <string>

               inline std::string CgalFailureStack(const CGAL::Failure_exception& failure)
               {
                   return failure.filename() + ":" + std::to_string(failure.line_number());
               }
               """;
    }
}