// -----------------------------------------------------------------------
// <copyright file="FclSourceRenderer.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using TedToolkit.CppBindings.Generator.Semantics;

namespace TedToolkit.CppBindings.Fcl.Generator;

/// <summary>Renders the provider-private FCL ABI and managed projection.</summary>
internal static class FclSourceRenderer
{
    internal static string RenderManaged(FclProfile profile)
    {
        return $$"""
                 // <auto-generated />
                 #pragma warning disable

                 using System.Runtime.InteropServices;

                 namespace TedToolkit.CppBindings.Fcl;

                 public enum FclBvhReturnCode
                 {
                     BVH_OK = 0,
                     BVH_ERR_MODEL_OUT_OF_MEMORY = -1,
                     BVH_ERR_BUILD_OUT_OF_SEQUENCE = -2,
                     BVH_ERR_BUILD_EMPTY_MODEL = -3,
                     BVH_ERR_BUILD_EMPTY_PREVIOUS_FRAME = -4,
                     BVH_ERR_UNSUPPORTED_FUNCTION = -5,
                     BVH_ERR_UNUPDATED_MODEL = -6,
                     BVH_ERR_INCORRECT_DATA = -7,
                     BVH_ERR_UNKNOWN = -8,
                 }

                 [StructLayout(LayoutKind.Sequential, Size = 24, Pack = 8)]
                 public readonly struct FclVector3
                 {
                     private readonly double x;
                     private readonly double y;
                     private readonly double z;

                     public FclVector3(double x, double y, double z)
                     {
                         this.x = x;
                         this.y = y;
                         this.z = z;
                     }

                     public double X => x;

                     public double Y => y;

                     public double Z => z;
                 }

                 public sealed class FclModelBuildResult
                 {
                     internal FclModelBuildResult(
                         FclBvhReturnCode code,
                         global::TedToolkit.CppBindings.Owned<FclBvhModel>? model)
                     {
                         Code = code;
                         Model = model;
                     }

                     public FclBvhReturnCode Code { get; }

                     public global::TedToolkit.CppBindings.Owned<FclBvhModel>? Model { get; }
                 }

                 public readonly record struct FclContinuousCollisionResult(bool IsCollide, double TimeOfContact);

                 [StructLayout(LayoutKind.Sequential, Size = 8, Pack = 8)]
                 public unsafe struct FclBvhModel : global::TedToolkit.CppBindings.ICppRaii
                 {
                     private nint storage;

                     public static FclModelBuildResult Create(
                         ReadOnlySpan<double> vertexCoordinates,
                         ReadOnlySpan<nuint> triangleIndices)
                     {
                         if (vertexCoordinates.Length % 3 != 0)
                         {
                             throw new ArgumentException("Vertex coordinate length must be a multiple of three.", nameof(vertexCoordinates));
                         }

                         if (triangleIndices.Length % 3 != 0)
                         {
                             throw new ArgumentException("Triangle index length must be a multiple of three.", nameof(triangleIndices));
                         }

                         var vertexCount = (nuint)(vertexCoordinates.Length / 3);
                         foreach (var index in triangleIndices)
                         {
                             if (index >= vertexCount)
                             {
                                 throw new ArgumentOutOfRangeException(nameof(triangleIndices), index,
                                     "A triangle index must be less than the vertex count.");
                             }
                         }

                         var owner = new global::TedToolkit.CppBindings.Owned<FclBvhModel>(
                             (delegate* unmanaged[Cdecl]<FclBvhModel*, void>)NativeApi.GetFunction(1));
                         var constructed = false;
                         try
                         {
                             global::TedToolkit.CppBindings.NativeError error = default;
                             int code;
                             fixed (FclBvhModel* resultPointer = &owner.Value)
                             fixed (double* vertexPointer = vertexCoordinates)
                             fixed (nuint* indexPointer = triangleIndices)
                             {
                                 code = ((delegate* unmanaged[Cdecl]<FclBvhModel*, double*, nuint, nuint*, nuint,
                                     global::TedToolkit.CppBindings.NativeError*, int>)NativeApi.GetFunction(2))(
                                         resultPointer,
                                         vertexPointer,
                                         (nuint)vertexCoordinates.Length,
                                         indexPointer,
                                         (nuint)triangleIndices.Length,
                                         &error);
                                 NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                             }

                             if (code != (int)FclBvhReturnCode.BVH_OK)
                             {
                                 GC.SuppressFinalize(owner);
                                 return new FclModelBuildResult((FclBvhReturnCode)code, null);
                             }

                             constructed = true;
                             return new FclModelBuildResult(FclBvhReturnCode.BVH_OK, owner);
                         }
                         finally
                         {
                             if (!constructed)
                             {
                                 GC.SuppressFinalize(owner);
                             }
                         }
                     }
                 }

                 public static unsafe class FclContinuousCollision
                 {
                     public static FclContinuousCollisionResult Query(
                         global::TedToolkit.CppBindings.Owned<FclBvhModel> first,
                         global::TedToolkit.CppBindings.Owned<FclBvhModel> second,
                         FclVector3 secondTranslation)
                     {
                         ArgumentNullException.ThrowIfNull(first);
                         ArgumentNullException.ThrowIfNull(second);
                         global::TedToolkit.CppBindings.NativeError error = default;
                         byte isCollide = 0;
                         double timeOfContact = 1;
                         fixed (FclBvhModel* firstPointer = &first.Value)
                         fixed (FclBvhModel* secondPointer = &second.Value)
                         {
                             ((delegate* unmanaged[Cdecl]<FclBvhModel*, FclBvhModel*, FclVector3*, byte*, double*,
                                 global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(3))(
                                     firstPointer, secondPointer, &secondTranslation, &isCollide, &timeOfContact, &error);
                             GC.KeepAlive(first);
                             GC.KeepAlive(second);
                         }

                         NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                         return new FclContinuousCollisionResult(isCollide != 0, timeOfContact);
                     }
                 }

                 internal static unsafe class NativeApi
                 {
                     private static readonly nint Module = NativeLibrary.Load(
                         "{{profile.NativeLibraryBaseName}}", typeof(NativeApi).Assembly, null);
                     private static readonly nint* Functions = ((delegate* unmanaged[Cdecl]<nint*>)NativeLibrary.GetExport(
                         Module, "NativeApi_GetFunctionTable"))();

                     internal static delegate* unmanaged[Cdecl]<global::TedToolkit.CppBindings.NativeError*, void> ClearError
                         => (delegate* unmanaged[Cdecl]<global::TedToolkit.CppBindings.NativeError*, void>)GetFunction(0);

                     internal static nint GetFunction(int index) => Functions[index];
                 }
                 """;
    }

    internal static string RenderNative(IReadOnlyList<string> functions)
    {
        var functionPointers = string.Join(",\n", functions.Select(static value =>
            $"    reinterpret_cast<std::uintptr_t>(&{value})"));
        var standardCatches = BindingNativeErrorCatchEmitter.Render(
            "SetError",
            "error",
            unknownMessageExpression: "\"Unknown native FCL exception.\"");
        return $$"""
                 // <auto-generated />
                 #include <fcl/fcl.h>

                 #include <atomic>
                 #include <cstddef>
                 #include <cstdint>
                 #include <cstdlib>
                 #include <cstring>
                 #include <exception>
                 #include <memory>
                 #include <new>
                 #include <stdexcept>
                 #include <type_traits>
                 #include <utility>
                 #include <vector>

                 struct NativeError
                 {
                     int Kind;
                     char* TypeName;
                     char* Message;
                     char* StackTrace;
                 };

                 struct FclVector3Transport
                 {
                     double X;
                     double Y;
                     double Z;
                 };

                 using Model = fcl::BVHModel<fcl::OBBRSS<double>>;
                 static std::atomic<int> ModelCreateCount = 0;
                 static std::atomic<int> ModelDestroyCount = 0;

                 struct CountedModel
                 {
                     std::unique_ptr<Model> Value;

                     CountedModel() : Value(std::make_unique<Model>()) { ++ModelCreateCount; }
                     ~CountedModel() noexcept { if (Value) ++ModelDestroyCount; }
                 };

                 struct FclBvhModelAdapter
                 {
                     Model* Value;

                     explicit FclBvhModelAdapter(CountedModel&& value) noexcept : Value(value.Value.release()) {}
                     ~FclBvhModelAdapter() noexcept { delete Value; ++ModelDestroyCount; }
                     FclBvhModelAdapter(const FclBvhModelAdapter&) = delete;
                     FclBvhModelAdapter& operator=(const FclBvhModelAdapter&) = delete;
                 };

                 static_assert(sizeof(FclVector3Transport) == 24 && alignof(FclVector3Transport) == 8);
                 static_assert(offsetof(FclVector3Transport, X) == 0);
                 static_assert(offsetof(FclVector3Transport, Y) == 8);
                 static_assert(offsetof(FclVector3Transport, Z) == 16);
                 static_assert(sizeof(fcl::Vector3<double>) == 24 && alignof(fcl::Vector3<double>) == 8);
                 static_assert(sizeof(FclBvhModelAdapter) == 8 && alignof(FclBvhModelAdapter) == 8);
                 static_assert(sizeof(std::size_t) == 8);
                 static_assert(std::is_same_v<std::underlying_type_t<fcl::BVHReturnCode>, int>);
                 static_assert(fcl::BVH_OK == 0);
                 static_assert(fcl::BVH_ERR_MODEL_OUT_OF_MEMORY == -1);
                 static_assert(fcl::BVH_ERR_BUILD_OUT_OF_SEQUENCE == -2);
                 static_assert(fcl::BVH_ERR_BUILD_EMPTY_MODEL == -3);
                 static_assert(fcl::BVH_ERR_BUILD_EMPTY_PREVIOUS_FRAME == -4);
                 static_assert(fcl::BVH_ERR_UNSUPPORTED_FUNCTION == -5);
                 static_assert(fcl::BVH_ERR_UNUPDATED_MODEL == -6);
                 static_assert(fcl::BVH_ERR_INCORRECT_DATA == -7);
                 static_assert(fcl::BVH_ERR_UNKNOWN == -8);

                 static char* CopyText(const char* value) noexcept
                 {
                     if (value == nullptr) return nullptr;
                     const auto length = std::strlen(value) + 1;
                     auto* copy = static_cast<char*>(std::malloc(length));
                     if (copy != nullptr) std::memcpy(copy, value, length);
                     return copy;
                 }

                 static void SetError(NativeError* error, int kind, const char* type, const char* message) noexcept
                 {
                     if (error == nullptr) return;
                     error->Kind = kind;
                     error->TypeName = CopyText(type);
                     error->Message = CopyText(message);
                     error->StackTrace = nullptr;
                 }

                 template<typename T, typename Callback>
                 static T Guard(NativeError* error, T fallback, Callback&& callback) noexcept
                 {
                     try { return callback(); }
                 {{standardCatches}}
                     return fallback;
                 }

                 extern "C" void Fcl_NativeError_Clear(NativeError* error) noexcept
                 {
                     if (error == nullptr) return;
                     std::free(error->TypeName);
                     std::free(error->Message);
                     std::free(error->StackTrace);
                     *error = {};
                 }

                 extern "C" void Fcl_Model_Destroy(FclBvhModelAdapter* value) noexcept
                 {
                     if (value != nullptr) value->~FclBvhModelAdapter();
                 }

                 extern "C" int Fcl_Model_Create(
                     FclBvhModelAdapter* result,
                     const double* coordinates,
                     std::size_t coordinateCount,
                     const std::size_t* indices,
                     std::size_t indexCount,
                     NativeError* error) noexcept
                 {
                     return Guard<int>(error, fcl::BVH_ERR_UNKNOWN, [&]()
                     {
                         CountedModel model;
                         std::vector<fcl::Vector3<double>> vertices;
                         vertices.reserve(coordinateCount / 3);
                         for (std::size_t index = 0; index < coordinateCount; index += 3)
                             vertices.emplace_back(coordinates[index], coordinates[index + 1], coordinates[index + 2]);
                         std::vector<fcl::Triangle> triangles;
                         triangles.reserve(indexCount / 3);
                         for (std::size_t index = 0; index < indexCount; index += 3)
                             triangles.emplace_back(
                                 static_cast<int>(indices[index]),
                                 static_cast<int>(indices[index + 1]),
                                 static_cast<int>(indices[index + 2]));

                         auto code = model.Value->beginModel();
                         if (code == fcl::BVH_OK) code = model.Value->addSubModel(vertices, triangles);
                         if (code == fcl::BVH_OK) code = model.Value->endModel();
                         if (code != fcl::BVH_OK) return code;
                         new (result) FclBvhModelAdapter(std::move(model));
                         return static_cast<int>(fcl::BVH_OK);
                     });
                 }

                 extern "C" void Fcl_ContinuousCollision_Query(
                     const FclBvhModelAdapter* first,
                     const FclBvhModelAdapter* second,
                     const FclVector3Transport* translation,
                     std::uint8_t* isCollide,
                     double* timeOfContact,
                     NativeError* error) noexcept
                 {
                     Guard<int>(error, 0, [&]()
                     {
                         const fcl::CollisionObject<double> firstObject(
                             std::make_shared<Model>(*first->Value), fcl::Transform3<double>::Identity());
                         const fcl::CollisionObject<double> secondObject(
                             std::make_shared<Model>(*second->Value), fcl::Transform3<double>::Identity());
                         fcl::ContinuousCollisionRequest<double> request;
                         request.ccd_motion_type = fcl::CCDM_LINEAR;
                         request.ccd_solver_type = fcl::CCDC_CONSERVATIVE_ADVANCEMENT;
                         fcl::ContinuousCollisionResult<double> result;
                         const auto firstEnd = fcl::Transform3<double>::Identity();
                         auto secondEnd = fcl::Transform3<double>::Identity();
                         secondEnd.translation() = fcl::Vector3<double>(translation->X, translation->Y, translation->Z);
                         fcl::continuousCollide(&firstObject, firstEnd, &secondObject, secondEnd, request, result);
                         if (!result.is_collide)
                         {
                             // FCL 0.7's oriented mesh conservative-advancement traversal can
                             // normalize a zero separation vector at first contact and lose a
                             // pure-translation hit. Confirm only that miss through FCL's exact
                             // translation solver; t == 1 intentionally remains the profile's
                             // documented endpoint ambiguity.
                             auto fallbackRequest = request;
                             fallbackRequest.ccd_motion_type = fcl::CCDM_TRANS;
                             fallbackRequest.ccd_solver_type = fcl::CCDC_POLYNOMIAL_SOLVER;
                             fcl::ContinuousCollisionResult<double> fallbackResult;
                             fcl::continuousCollide(
                                 &firstObject, firstEnd, &secondObject, secondEnd, fallbackRequest, fallbackResult);
                             if (fallbackResult.is_collide && fallbackResult.time_of_contact < 1.0)
                                 result = fallbackResult;
                         }

                         *isCollide = result.is_collide ? 1 : 0;
                         *timeOfContact = result.is_collide ? result.time_of_contact : 1.0;
                         return 1;
                     });
                 }

                 extern "C" void Fcl_Lifetime_Reset() noexcept { ModelCreateCount = 0; ModelDestroyCount = 0; }
                 extern "C" int Fcl_Lifetime_CreateCount() noexcept { return ModelCreateCount.load(); }
                 extern "C" int Fcl_Lifetime_DestroyCount() noexcept { return ModelDestroyCount.load(); }

                 extern "C" __declspec(dllexport) const std::uintptr_t* NativeApi_GetFunctionTable() noexcept
                 {
                     static const std::uintptr_t Functions[] =
                     {
                 {{functionPointers}}
                     };
                     return Functions;
                 }
                 """;
    }

    internal static string RenderCMake(FclProfile profile)
    {
        return $$"""
                 cmake_minimum_required(VERSION 3.28)
                 project(TedToolkitCppBindingsFcl LANGUAGES CXX)

                 file(WRITE "${CMAKE_BINARY_DIR}/compiler-identity.txt"
                     "${CMAKE_CXX_COMPILER_ID}|${CMAKE_CXX_COMPILER_VERSION}|${CMAKE_CXX_COMPILER}")

                 find_package(fcl CONFIG REQUIRED)
                 add_library({{profile.NativeLibraryBaseName}} SHARED FclProfileAdapter.cpp)
                 target_compile_features({{profile.NativeLibraryBaseName}} PRIVATE cxx_std_20)
                 target_compile_options({{profile.NativeLibraryBaseName}} PRIVATE /MP1)
                 target_link_libraries({{profile.NativeLibraryBaseName}} PRIVATE fcl)
                 """;
    }
}