// -----------------------------------------------------------------------
// <copyright file="CgalSemanticProfile.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using TedToolkit.CppBindings.Generator.Semantics;

namespace TedToolkit.CppBindings.Cgal.Generator;

/// <summary>
/// Supplies finite CGAL policies to Shared without adding provider knowledge there.
/// </summary>
internal static class CgalSemanticProfile
{
    /// <summary>
    /// The managed source-stem emitter identity.
    /// </summary>
    internal const string ManagedSourceStem = "managed-source-stem";

    /// <summary>
    /// The native source-stem emitter identity.
    /// </summary>
    internal const string NativeSourceStem = "native-source-stem";

    /// <summary>
    /// Creates the configured provider-neutral semantic engine.
    /// </summary>
    /// <returns>The configured engine.</returns>
    internal static BindingSemanticEngine Create()
    {
        return new(
            [new TypeRule(),],
            new LayoutPolicy(),
            new TemplatePolicy(),
            [new SourceStemEmitter(ManagedSourceStem), new SourceStemEmitter(NativeSourceStem),]);
    }

    /// <summary>
    /// Creates the immutable emission policy for the selected namespace.
    /// </summary>
    /// <param name="cSharpNamespace">The generated managed namespace.</param>
    /// <param name="isInternal">Whether generated declarations are internal.</param>
    /// <returns>The provider emission profile.</returns>
    internal static BindingEmissionProfile CreateEmissionProfile(string cSharpNamespace, bool isInternal)
    {
        return new()
        {
            CSharpNamespace = cSharpNamespace,
            IsInternal = isInternal,
            ManagedNativeErrorProjection = "global::TedToolkit.CppBindings.Cgal.NativeErrorProjection",
            NativeErrorClearExport = "Cgal_NativeError_Clear",
            NativePreamble = "// <auto-generated />\n",
            NativeErrorPreamble = "#include \"CgalNativeError.hpp\"\n#include <exception>\n#include <new>\n#include <stdexcept>\n",
            NativeErrorType = "NativeError",
            NativeErrorSetter = "Cgal_NativeError_Set",
            NativeExceptionProjections =
            [
                Failure("CGAL::Error_exception", 10),
                Failure("CGAL::Precondition_exception", 11),
                Failure("CGAL::Postcondition_exception", 12),
                Failure("CGAL::Assertion_exception", 13),
                Failure("CGAL::Test_exception", 14),
                Failure("CGAL::Warning_exception", 15),
                Failure("CGAL::Failure_exception", 16),
                Standard("std::invalid_argument", 1),
                Standard("std::out_of_range", 2),
                Standard("std::bad_alloc", 6),
                Standard("std::overflow_error", 7),
                Standard("std::underflow_error", 7),
                Standard("std::exception", 9),
            ],
            UnknownNativeExceptionCode = 255,
            UnknownNativeStackExpression = "nullptr",
        };
    }

    private static BindingNativeExceptionProjection Failure(string type, int code)
    {
        return new(type, code, $"\"{type}\"", "exception.what()", "CgalFailureStack(exception).c_str()");
    }

    private static BindingNativeExceptionProjection Standard(string type, int code)
    {
        return new(type, code, $"\"{type}\"", "exception.what()", "nullptr");
    }

    private sealed class TypeRule : IBindingTypeRule
    {
        public bool TryResolve(CppTypeDescriptor type, out BindingTypeProjection? projection)
        {
            projection = new(type.NativeName, type.NativeName);
            return true;
        }
    }

    private sealed class LayoutPolicy : IBindingLayoutPolicy
    {
        public BindingAdmission Admit(BindingLayoutDescriptor layout)
        {
            return layout.Alignment is 1 or 2 or 4 or 8
                ? BindingAdmission.Admitted
                : BindingAdmission.Reject($"Unsupported win-x64 alignment {layout.Alignment}.");
        }
    }

    private sealed class TemplatePolicy : IBindingTemplatePolicy
    {
        public BindingAdmission Admit(BindingTemplateDescriptor template)
        {
            return template.IsClosed
                ? BindingAdmission.Admitted
                : BindingAdmission.Reject("The CGAL profile admits only explicit closed template instances.");
        }
    }

    private sealed class SourceStemEmitter(string name) : IBindingEmitterPrimitive
    {
        /// <inheritdoc />
        public string Name
        {
            get
            {
                return name;
            }
        }

        /// <inheritdoc />
        public string Emit(string value)
        {
            return value.Replace("::", "_", StringComparison.Ordinal);
        }
    }
}