<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\externals\TedToolkit\props\CodeAnalysis.props"/>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);RCS1046</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\shared\TedToolkit.CppBindings.Runtime\TedToolkit.CppBindings.Runtime.csproj" />
    <ProjectReference Include="..\..\src\providers\occt\TedToolkit.CppBindings.Occt.Runtime\TedToolkit.CppBindings.Occt.Runtime.csproj" />
    <ProjectReference Include="..\TedToolkit.CppBindings.Runtime.FirstWrapper\TedToolkit.CppBindings.Runtime.FirstWrapper.csproj" />
    <ProjectReference Include="..\TedToolkit.CppBindings.Runtime.SecondWrapper\TedToolkit.CppBindings.Runtime.SecondWrapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

</Project>
