// -----------------------------------------------------------------------
// <copyright file="NativeErrorSupportGenerator.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

namespace TedToolkit.CppBindings.Occt.Generator.Generators;

/// <summary>
/// Generates the type-independent native error transport used by throwing exports.
/// </summary>
internal static class NativeErrorSupportGenerator
{
    /// <summary>
    /// Gets the generated transport header file name.
    /// </summary>
    public const string HeaderFileName = "NativeError.h";

    /// <summary>
    /// Gets the generated transport implementation file name.
    /// </summary>
    public const string SourceFileName = "NativeError.cpp";

    /// <summary>
    /// Generates the native transport declarations.
    /// </summary>
    /// <returns>The complete header source.</returns>
    public static string GenerateHeader()
    {
        return """
            // <auto-generated />
            #pragma once

            struct NativeError
            {
                int Kind;
                char* TypeName;
                char* Message;
                char* StackTrace;
            };

            extern "C" void NativeError_Clear(NativeError* error) noexcept;
            extern "C" void NativeError_Set(
                NativeError* error,
                int kind,
                const char* typeName,
                const char* message) noexcept;
            """;
    }

    /// <summary>
    /// Generates the native transport implementation.
    /// </summary>
    /// <returns>The complete C++ source.</returns>
    public static string GenerateSource()
    {
        return """
            // <auto-generated />
            #include "NativeError.h"

            #include <cstdlib>
            #include <cstring>

            static char* NativeError_Copy(const char* value) noexcept
            {
                if (value == nullptr)
                {
                    return nullptr;
                }

                const auto length = std::strlen(value) + 1;
                auto* copy = static_cast<char*>(std::malloc(length));
                if (copy != nullptr)
                {
                    std::memcpy(copy, value, length);
                }

                return copy;
            }

            extern "C" void NativeError_Clear(NativeError* error) noexcept
            {
                if (error == nullptr)
                {
                    return;
                }

                std::free(error->TypeName);
                std::free(error->Message);
                std::free(error->StackTrace);
                *error = {};
            }

            extern "C" void NativeError_Set(
                NativeError* error,
                int kind,
                const char* typeName,
                const char* message) noexcept
            {
                if (error == nullptr)
                {
                    return;
                }

                error->Kind = kind;
                error->TypeName = NativeError_Copy(typeName);
                error->Message = NativeError_Copy(message);
                error->StackTrace = nullptr;
            }
            """;
    }
}