<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\externals\TedToolkit\props\CodeAnalysis.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Fixtures\**\*.cs" />
    <ProjectReference Include="..\..\src\shared\TedToolkit.CppBindings.Generator\TedToolkit.CppBindings.Generator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

</Project>
