// -----------------------------------------------------------------------
// <copyright file="CppGenerator.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

using TedToolkit.Occt.Generator.Models.Declarations;
using TedToolkit.Occt.Generator.Models.Types;
using TedToolkit.RoslynHelper.Generators;

namespace TedToolkit.Occt.Generator.Generators;

/// <summary>
/// Generates the internal C++ invocation helpers for one parsed record.
/// </summary>
/// <remarks>
/// These helpers deliberately have C++ linkage and are not the public C transport boundary.
/// A later projection stage supplies validated C transports before exported wrappers are emitted.
/// </remarks>
/// <param name="record">The parsed record that remains the declaration authority.</param>
internal sealed class CppGenerator(RecordModel record) : IGenerator
{
    /// <inheritdoc />
    public Task<string> GenerateAsync(CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var builder = new StringBuilder("// <auto-generated />\n#include <utility>\n");
        foreach (var header in GetRequiredHeaders(record))
        {
            _ = builder.Append("#include <").Append(header).Append(">\n");
        }

        _ = builder.Append("\nnamespace ted_toolkit::occt::generated\n{\n");
        for (var index = 0; index < record.MethodModels.Count; index++)
        {
            AppendMethod(builder, record.MethodModels[index], index);
        }

        return Task.FromResult(builder.Append("}\n").ToString());
    }

    private static IEnumerable<string> GetRequiredHeaders(RecordModel recordModel)
    {
        var headers = new HashSet<string>(StringComparer.Ordinal) { recordModel.SourceHeader, };
        AddHeaders(headers, recordModel.Type);
        foreach (var field in recordModel.FieldModels)
        {
            AddHeaders(headers, field.Type);
        }

        foreach (var method in recordModel.MethodModels)
        {
            AddHeaders(headers, method.ReturnType);
            foreach (var parameter in method.Parameters)
            {
                AddHeaders(headers, parameter.Type);
            }
        }

        return headers.Order(StringComparer.Ordinal);
    }

    private static void AddHeaders(HashSet<string> headers, TypeModel type)
    {
        foreach (var header in type.RequiredHeaders)
        {
            _ = headers.Add(header);
        }
    }

    private void AppendMethod(StringBuilder builder, MethodModel method, int index)
    {
        switch (method.Type)
        {
            case MethodModelType.NEW:
                AppendConstructor(builder, method, index);
                return;

            case MethodModelType.DELETE:
                _ = builder.Append("void destroy_").Append(index).Append('(')
                    .Append(record.Type.CppTypeName).Append("* self)\n{\n    delete self;\n}\n\n");
                return;

            case MethodModelType.NORMAL:
            case MethodModelType.OPERATOR:
            case MethodModelType.IMPLICIT:
            case MethodModelType.EXPLICIT:
                AppendInvocation(builder, method, index);
                return;

            default:
                throw new InvalidOperationException($"Unsupported method model type '{method.Type}'.");
        }
    }

    private void AppendConstructor(StringBuilder builder, MethodModel method, int index)
    {
        _ = builder.Append(record.Type.CppTypeName).Append("* create_").Append(index).Append('(');
        AppendParameters(builder, method.Parameters, includeReceiver: false, method.IsConst);
        _ = builder.Append(")\n{\n    return new ").Append(record.Type.CppTypeName).Append('(');
        AppendArguments(builder, method.Parameters);
        _ = builder.Append(");\n}\n\n");
    }

    private void AppendInvocation(StringBuilder builder, MethodModel method, int index)
    {
        _ = builder.Append(method.ReturnType.CppTypeName).Append(" invoke_").Append(index).Append('(');
        AppendParameters(builder, method.Parameters, !method.IsStatic, method.IsConst);
        _ = builder.Append(")\n{\n    ");
        if (!method.IsReturnVoid)
        {
            _ = builder.Append("return ");
        }

        if (method.Type is MethodModelType.IMPLICIT or MethodModelType.EXPLICIT)
        {
            _ = builder.Append("static_cast<").Append(method.ReturnType.CppTypeName).Append(">(self)");
        }
        else if (method.Type is MethodModelType.OPERATOR)
        {
            _ = builder.Append("self.operator").Append(method.MethodName);
            AppendCallArguments(builder, method.Parameters);
        }
        else
        {
            _ = builder.Append(method.IsStatic ? record.Type.CppTypeName + "::" : "self.")
                .Append(method.MethodName);
            AppendCallArguments(builder, method.Parameters);
        }

        _ = builder.Append(";\n}\n\n");
    }

    private void AppendParameters(
        StringBuilder builder,
        IReadOnlyList<ParameterModel> parameters,
        bool includeReceiver,
        bool receiverIsConst)
    {
        var started = false;
        if (includeReceiver)
        {
            if (receiverIsConst)
            {
                _ = builder.Append("const ");
            }

            _ = builder.Append(record.Type.CppTypeName).Append("& self");
            started = true;
        }

        foreach (var parameter in parameters)
        {
            if (started)
            {
                _ = builder.Append(", ");
            }

            _ = builder.Append(parameter.Type.CppTypeName).Append(' ').Append(parameter.Name);
            started = true;
        }
    }

    private static void AppendCallArguments(StringBuilder builder, IReadOnlyList<ParameterModel> parameters)
    {
        _ = builder.Append('(');
        AppendArguments(builder, parameters);
        _ = builder.Append(')');
    }

    private static void AppendArguments(StringBuilder builder, IReadOnlyList<ParameterModel> parameters)
    {
        for (var index = 0; index < parameters.Count; index++)
        {
            if (index > 0)
            {
                _ = builder.Append(", ");
            }

            var parameter = parameters[index];
            if (parameter.Type.CppTypeName.TrimEnd().EndsWith("&&", StringComparison.Ordinal))
            {
                _ = builder.Append("std::move(").Append(parameter.Name).Append(')');
            }
            else
            {
                _ = builder.Append(parameter.Name);
            }
        }
    }
}