// -----------------------------------------------------------------------
// <copyright file="NativeFunctionTableGenerator.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

namespace TedToolkit.Occt.Generator.Generators;

/// <summary>
/// Generates the single exported native function-table entry point.
/// </summary>
internal static class NativeFunctionTableGenerator
{
    /// <summary>
    /// Gets the generated source file name.
    /// </summary>
    public const string FileName = "NativeFunctionTable.cpp";

    /// <summary>
    /// Generates the native function table in the same deterministic order as managed loading.
    /// </summary>
    /// <param name="exports">The native function names.</param>
    /// <returns>The complete C++ source.</returns>
    public static string Generate(IReadOnlyList<string> exports)
    {
        ArgumentNullException.ThrowIfNull(exports);
        var builder = new StringBuilder("// <auto-generated />\n#include <cstdint>\n\n");
        foreach (var export in exports)
        {
            _ = builder.Append("extern \"C\" void ").Append(export).Append("();\n");
        }

        _ = builder.Append("\nstatic const std::uintptr_t Functions[] =\n{\n");
        foreach (var export in exports)
        {
            _ = builder.Append("    reinterpret_cast<std::uintptr_t>(&").Append(export).Append("),\n");
        }

        _ = builder.Append(
            "};\n\nextern \"C\" __declspec(dllexport) const std::uintptr_t* "
            + "NativeApi_GetFunctionTable() noexcept\n{\n    return Functions;\n}\n");
        return builder.ToString();
    }
}