// -----------------------------------------------------------------------
// <copyright file="NativeApiGenerator.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

using TedToolkit.Occt.Generator.Models.Declarations;

namespace TedToolkit.Occt.Generator.Generators;

/// <summary>
/// Generates the process-lifetime native module and complete export table.
/// </summary>
internal static class NativeApiGenerator
{
    /// <summary>
    /// Gets the generated source file name.
    /// </summary>
    public const string FileName = "NativeApi.g.cs";

    /// <summary>
    /// Generates the complete native export table.
    /// </summary>
    /// <param name="records">The completed declaration models.</param>
    /// <param name="nativeLibraryBaseName">The validated native library basename.</param>
    /// <returns>The complete C# source.</returns>
    public static string Generate(IReadOnlyList<RecordModel> records, string nativeLibraryBaseName)
    {
        ArgumentNullException.ThrowIfNull(records);
        ArgumentException.ThrowIfNullOrEmpty(nativeLibraryBaseName);

        var builder = new StringBuilder(
            "// <auto-generated />\n#pragma warning disable\n\n"
            + "using System.Runtime.InteropServices;\n\n"
            + "namespace TedToolkit.Occt;\n\n"
            + "internal static unsafe class NativeApi\n{\n"
            + "    private static readonly nint Module = NativeLibrary.Load(\"");
        _ = builder.Append(Escape(nativeLibraryBaseName))
            .Append("\", typeof(NativeApi).Assembly, null);\n")
            .Append("    private static readonly nint* Functions = "
                + "((delegate* unmanaged[Cdecl]<nint*>)NativeLibrary.GetExport("
                + "Module, \"NativeApi_GetFunctionTable\"))();\n\n"
                + "    internal static nint GetFunction(int index) => Functions[index];\n"
                + "}\n");
        return builder.ToString();
    }

    /// <summary>
    /// Gets every native function in deterministic function-table order.
    /// </summary>
    /// <param name="records">The completed declaration models.</param>
    /// <returns>The ordered unique native function names.</returns>
    /// <exception cref="InvalidOperationException">A native function name is duplicated.</exception>
    internal static string[] GetExports(IReadOnlyList<RecordModel> records)
    {
        var exports = new HashSet<string>(StringComparer.Ordinal) { "NativeError_Clear", };
        foreach (var record in records.OrderBy(static value => value.Type.CSharpTypeName, StringComparer.Ordinal))
        {
            foreach (var method in record.MethodModels)
            {
                if (!exports.Add(method.NativeExportName))
                {
                    throw new InvalidOperationException($"Duplicate native export '{method.NativeExportName}'.");
                }
            }

            foreach (var relation in record.Bases.Where(static value =>
                         value.IsPublic
                         && value.PointerAdjustment is PointerAdjustmentKind.NativeAdjust))
            {
                var export = NativeExportNameBuilder.GetPointerAdjustmentName(record, relation.Base);
                if (!exports.Add(export))
                {
                    throw new InvalidOperationException($"Duplicate native export '{export}'.");
                }
            }
        }

        return exports.Order(StringComparer.Ordinal).ToArray();
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }
}