// -----------------------------------------------------------------------
// <copyright file="ManifoldSourceRenderer.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using TedToolkit.CppBindings.Generator.Semantics;

namespace TedToolkit.CppBindings.Manifold.Generator;

/// <summary>
/// Renders the provider-private ABI and its managed projection.
/// </summary>
internal static class ManifoldSourceRenderer
{
    internal static string RenderManaged(ManifoldProfile profile)
    {
        return $$"""
                 // <auto-generated />
                 #pragma warning disable

                 using System.Runtime.InteropServices;

                 namespace TedToolkit.CppBindings.Manifold;

                 public enum ManifoldOp : sbyte
                 {
                     Add = 0,
                     Subtract = 1,
                     Intersect = 2,
                 }

                 public enum ManifoldError
                 {
                     NoError = 0,
                     NonFiniteVertex = 1,
                     NotManifold = 2,
                     VertexOutOfBounds = 3,
                     PropertiesWrongLength = 4,
                     MissingPositionProperties = 5,
                     MergeVectorsDifferentLengths = 6,
                     MergeIndexOutOfBounds = 7,
                     TransformWrongLength = 8,
                     RunIndexWrongLength = 9,
                     FaceIDWrongLength = 10,
                     InvalidConstruction = 11,
                     ResultTooLarge = 12,
                     InvalidTangents = 13,
                     Cancelled = 14,
                 }

                 public sealed class ManifoldMeshData
                 {
                     internal ManifoldMeshData(double[] vertexCoordinates, ulong[] triangleIndices)
                     {
                         VertexCoordinates = vertexCoordinates;
                         TriangleIndices = triangleIndices;
                     }

                     public double[] VertexCoordinates { get; }

                     public ulong[] TriangleIndices { get; }

                     public int PositionPropertyCount => 3;
                 }

                 [StructLayout(LayoutKind.Sequential, Size = 8, Pack = 8)]
                 public unsafe struct Manifold : global::TedToolkit.CppBindings.ICppRaii
                 {
                     private nint Storage;

                     public static global::TedToolkit.CppBindings.Owned<Manifold> Create(
                         ReadOnlySpan<double> vertexCoordinates,
                         ReadOnlySpan<ulong> triangleIndices)
                     {
                         if (vertexCoordinates.Length % 3 != 0)
                         {
                             throw new ArgumentException("Vertex coordinate length must be a multiple of three.", nameof(vertexCoordinates));
                         }

                         if (triangleIndices.Length % 3 != 0)
                         {
                             throw new ArgumentException("Triangle index length must be a multiple of three.", nameof(triangleIndices));
                         }

                         var result = new global::TedToolkit.CppBindings.Owned<Manifold>(
                             (delegate* unmanaged[Cdecl]<Manifold*, void>)NativeApi.GetFunction(1));
                         var constructed = false;
                         try
                         {
                             global::TedToolkit.CppBindings.NativeError error = default;
                             fixed (Manifold* resultPointer = &result.Value)
                             fixed (double* vertexPointer = vertexCoordinates)
                             fixed (ulong* indexPointer = triangleIndices)
                             {
                                 ((delegate* unmanaged[Cdecl]<Manifold*, double*, nuint, ulong*, nuint,
                                     global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(2))(
                                         resultPointer,
                                         vertexPointer,
                                         (nuint)vertexCoordinates.Length,
                                         indexPointer,
                                         (nuint)triangleIndices.Length,
                                         &error);
                                 NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                             }

                             constructed = true;
                             return result;
                         }
                         finally
                         {
                             if (!constructed)
                             {
                                 GC.SuppressFinalize(result);
                             }
                         }
                     }
                 }

                 public static unsafe class ManifoldExtensions
                 {
                     public static ManifoldError Status(this global::TedToolkit.CppBindings.Owned<Manifold> self)
                     {
                         ArgumentNullException.ThrowIfNull(self);
                         global::TedToolkit.CppBindings.NativeError error = default;
                         fixed (Manifold* selfPointer = &self.Value)
                         {
                             var result = ((delegate* unmanaged[Cdecl]<Manifold*,
                                 global::TedToolkit.CppBindings.NativeError*, int>)NativeApi.GetFunction(3))(
                                     selfPointer, &error);
                             GC.KeepAlive(self);
                             NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                             return (ManifoldError)result;
                         }
                     }

                     public static global::TedToolkit.CppBindings.Owned<Manifold> Boolean(
                         this global::TedToolkit.CppBindings.Owned<Manifold> self,
                         global::TedToolkit.CppBindings.Owned<Manifold> second,
                         ManifoldOp operation)
                     {
                         ArgumentNullException.ThrowIfNull(self);
                         ArgumentNullException.ThrowIfNull(second);
                         if (!Enum.IsDefined(operation))
                         {
                             throw new ArgumentOutOfRangeException(nameof(operation));
                         }

                         return Construct(resultPointer =>
                         {
                             global::TedToolkit.CppBindings.NativeError error = default;
                             fixed (Manifold* selfPointer = &self.Value)
                             fixed (Manifold* secondPointer = &second.Value)
                             {
                                 ((delegate* unmanaged[Cdecl]<Manifold*, Manifold*, Manifold*, sbyte,
                                     global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(4))(
                                         resultPointer, selfPointer, secondPointer, (sbyte)operation, &error);
                                 GC.KeepAlive(self);
                                 GC.KeepAlive(second);
                                 NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                             }
                         });
                     }

                     public static global::TedToolkit.CppBindings.Owned<Manifold> Translate(
                         this global::TedToolkit.CppBindings.Owned<Manifold> self,
                         double x,
                         double y,
                         double z)
                     {
                         ArgumentNullException.ThrowIfNull(self);
                         return Construct(resultPointer =>
                         {
                             global::TedToolkit.CppBindings.NativeError error = default;
                             fixed (Manifold* selfPointer = &self.Value)
                             {
                                 ((delegate* unmanaged[Cdecl]<Manifold*, Manifold*, double, double, double,
                                     global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(5))(
                                         resultPointer, selfPointer, x, y, z, &error);
                                 GC.KeepAlive(self);
                                 NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                             }
                         });
                     }

                     public static nuint NumTri(this global::TedToolkit.CppBindings.Owned<Manifold> self)
                     {
                         ArgumentNullException.ThrowIfNull(self);
                         global::TedToolkit.CppBindings.NativeError error = default;
                         fixed (Manifold* selfPointer = &self.Value)
                         {
                             var result = ((delegate* unmanaged[Cdecl]<Manifold*,
                                 global::TedToolkit.CppBindings.NativeError*, nuint>)NativeApi.GetFunction(6))(
                                     selfPointer, &error);
                             GC.KeepAlive(self);
                             NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                             return result;
                         }
                     }

                     public static ManifoldMeshData GetMesh(this global::TedToolkit.CppBindings.Owned<Manifold> self)
                     {
                         ArgumentNullException.ThrowIfNull(self);
                         global::TedToolkit.CppBindings.NativeError error = default;
                         nuint vertexCoordinateCount = 0;
                         nuint triangleIndexCount = 0;
                         fixed (Manifold* selfPointer = &self.Value)
                         {
                             ((delegate* unmanaged[Cdecl]<Manifold*, nuint*, nuint*,
                                 global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(7))(
                                     selfPointer, &vertexCoordinateCount, &triangleIndexCount, &error);
                             GC.KeepAlive(self);
                         }

                         NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                         if (vertexCoordinateCount > int.MaxValue || triangleIndexCount > int.MaxValue)
                         {
                             throw new OverflowException("Native mesh exceeds the maximum managed array length.");
                         }

                         var vertices = new double[(int)vertexCoordinateCount];
                         var indices = new ulong[(int)triangleIndexCount];
                         fixed (Manifold* selfPointer = &self.Value)
                         fixed (double* vertexPointer = vertices)
                         fixed (ulong* indexPointer = indices)
                         {
                             ((delegate* unmanaged[Cdecl]<Manifold*, double*, nuint, ulong*, nuint,
                                 global::TedToolkit.CppBindings.NativeError*, void>)NativeApi.GetFunction(8))(
                                     selfPointer,
                                     vertexPointer,
                                     vertexCoordinateCount,
                                     indexPointer,
                                     triangleIndexCount,
                                     &error);
                             GC.KeepAlive(self);
                         }

                         NativeErrorProjection.ThrowIfFailed(ref error, NativeApi.ClearError);
                         return new ManifoldMeshData(vertices, indices);
                     }

                     private static global::TedToolkit.CppBindings.Owned<Manifold> Construct(
                         NativeConstructor constructor)
                     {
                         var result = new global::TedToolkit.CppBindings.Owned<Manifold>(
                             (delegate* unmanaged[Cdecl]<Manifold*, void>)NativeApi.GetFunction(1));
                         var constructed = false;
                         try
                         {
                             fixed (Manifold* resultPointer = &result.Value)
                             {
                                 constructor(resultPointer);
                             }

                             constructed = true;
                             return result;
                         }
                         finally
                         {
                             if (!constructed)
                             {
                                 GC.SuppressFinalize(result);
                             }
                         }
                     }

                     private delegate void NativeConstructor(Manifold* result);
                 }

                 internal static unsafe class NativeApi
                 {
                     private static readonly nint Module = NativeLibrary.Load(
                         "{{profile.NativeLibraryBaseName}}", typeof(NativeApi).Assembly, null);
                     private static readonly nint* Functions = ((delegate* unmanaged[Cdecl]<nint*>)NativeLibrary.GetExport(
                         Module, "NativeApi_GetFunctionTable"))();

                     internal static delegate* unmanaged[Cdecl]<global::TedToolkit.CppBindings.NativeError*, void> ClearError
                         => (delegate* unmanaged[Cdecl]<global::TedToolkit.CppBindings.NativeError*, void>)GetFunction(0);

                     internal static nint GetFunction(int index) => Functions[index];
                 }
                 """;
    }

    internal static string RenderNative(ManifoldProfile profile, IReadOnlyList<string> exports)
    {
        var functionPointers = string.Join(",\n", exports.Select(static value =>
            $"    reinterpret_cast<std::uintptr_t>(&{value})"));
        var standardCatches = BindingNativeErrorCatchEmitter.Render(
            "SetError",
            "error",
            unknownMessageExpression: "\"Unknown native Manifold exception.\"");
        return $$"""
                 // <auto-generated />
                 #include <manifold/manifold.h>
                 #include <manifold/mesh.h>

                 #include <algorithm>
                 #include <cstdint>
                 #include <cstdlib>
                 #include <cstring>
                 #include <exception>
                 #include <new>
                 #include <stdexcept>
                 #include <type_traits>
                 #include <utility>

                 struct NativeError
                 {
                     int Kind;
                     char* TypeName;
                     char* Message;
                     char* StackTrace;
                 };

                 struct ManifoldAdapter
                 {
                     manifold::Manifold* Value;

                     explicit ManifoldAdapter(const manifold::MeshGL64& mesh)
                         : Value(new manifold::Manifold(mesh)) {}

                     explicit ManifoldAdapter(manifold::Manifold&& value)
                         : Value(new manifold::Manifold(std::move(value))) {}

                     ~ManifoldAdapter() noexcept { delete Value; }

                     ManifoldAdapter(const ManifoldAdapter&) = delete;
                     ManifoldAdapter& operator=(const ManifoldAdapter&) = delete;
                 };

                 static_assert(sizeof(ManifoldAdapter) == 8 && alignof(ManifoldAdapter) == 8);
                 static_assert(sizeof(std::size_t) == 8);
                 static_assert(std::is_same_v<std::underlying_type_t<manifold::OpType>, char>);
                 static_assert(static_cast<int>(manifold::OpType::Add) == 0);
                 static_assert(static_cast<int>(manifold::OpType::Subtract) == 1);
                 static_assert(static_cast<int>(manifold::OpType::Intersect) == 2);
                 static_assert(std::is_same_v<std::underlying_type_t<manifold::Manifold::Error>, int>);
                 static_assert(static_cast<int>(manifold::Manifold::Error::NoError) == 0);
                 static_assert(static_cast<int>(manifold::Manifold::Error::NonFiniteVertex) == 1);
                 static_assert(static_cast<int>(manifold::Manifold::Error::NotManifold) == 2);
                 static_assert(static_cast<int>(manifold::Manifold::Error::VertexOutOfBounds) == 3);
                 static_assert(static_cast<int>(manifold::Manifold::Error::PropertiesWrongLength) == 4);
                 static_assert(static_cast<int>(manifold::Manifold::Error::MissingPositionProperties) == 5);
                 static_assert(static_cast<int>(manifold::Manifold::Error::MergeVectorsDifferentLengths) == 6);
                 static_assert(static_cast<int>(manifold::Manifold::Error::MergeIndexOutOfBounds) == 7);
                 static_assert(static_cast<int>(manifold::Manifold::Error::TransformWrongLength) == 8);
                 static_assert(static_cast<int>(manifold::Manifold::Error::RunIndexWrongLength) == 9);
                 static_assert(static_cast<int>(manifold::Manifold::Error::FaceIDWrongLength) == 10);
                 static_assert(static_cast<int>(manifold::Manifold::Error::InvalidConstruction) == 11);
                 static_assert(static_cast<int>(manifold::Manifold::Error::ResultTooLarge) == 12);
                 static_assert(static_cast<int>(manifold::Manifold::Error::InvalidTangents) == 13);
                 static_assert(static_cast<int>(manifold::Manifold::Error::Cancelled) == 14);

                 static char* CopyText(const char* value) noexcept
                 {
                     if (value == nullptr) return nullptr;
                     const auto length = std::strlen(value) + 1;
                     auto* copy = static_cast<char*>(std::malloc(length));
                     if (copy != nullptr) std::memcpy(copy, value, length);
                     return copy;
                 }

                 static void SetError(NativeError* error, int kind, const char* type, const char* message) noexcept
                 {
                     if (error == nullptr) return;
                     error->Kind = kind;
                     error->TypeName = CopyText(type);
                     error->Message = CopyText(message);
                     error->StackTrace = nullptr;
                 }

                 template<typename T, typename Callback>
                 static T Guard(NativeError* error, T fallback, Callback&& callback) noexcept
                 {
                     try
                     {
                         return callback();
                     }
                 {{standardCatches}}

                     return fallback;
                 }

                 extern "C" void Manifold_NativeError_Clear(NativeError* error) noexcept
                 {
                     if (error == nullptr) return;
                     std::free(error->TypeName);
                     std::free(error->Message);
                     std::free(error->StackTrace);
                     *error = {};
                 }

                 extern "C" void Manifold_Destroy(ManifoldAdapter* value) noexcept
                 {
                     if (value != nullptr) value->~ManifoldAdapter();
                 }

                 extern "C" void Manifold_Create(
                     ManifoldAdapter* result,
                     const double* vertices,
                     std::size_t vertexCount,
                     const std::uint64_t* indices,
                     std::size_t indexCount,
                     NativeError* error) noexcept
                 {
                     Guard<int>(error, 0, [&]()
                     {
                         manifold::MeshGL64 mesh;
                         if (vertexCount != 0) mesh.vertProperties.assign(vertices, vertices + vertexCount);
                         if (indexCount != 0) mesh.triVerts.assign(indices, indices + indexCount);
                         new (result) ManifoldAdapter(mesh);
                         return 1;
                     });
                 }

                 extern "C" int Manifold_Status(const ManifoldAdapter* value, NativeError* error) noexcept
                 {
                     return Guard<int>(error, 11, [&]() { return static_cast<int>(value->Value->Status()); });
                 }

                 extern "C" void Manifold_Boolean(
                     ManifoldAdapter* result,
                     const ManifoldAdapter* first,
                     const ManifoldAdapter* second,
                     signed char operation,
                     NativeError* error) noexcept
                 {
                     Guard<int>(error, 0, [&]()
                     {
                         if (operation < 0 || operation > 2) throw std::out_of_range("operation");
                         new (result) ManifoldAdapter(first->Value->Boolean(
                             *second->Value, static_cast<manifold::OpType>(operation)));
                         return 1;
                     });
                 }

                 extern "C" void Manifold_Translate(
                     ManifoldAdapter* result,
                     const ManifoldAdapter* value,
                     double x,
                     double y,
                     double z,
                     NativeError* error) noexcept
                 {
                     Guard<int>(error, 0, [&]()
                     {
                         new (result) ManifoldAdapter(value->Value->Translate(manifold::vec3(x, y, z)));
                         return 1;
                     });
                 }

                 extern "C" std::size_t Manifold_NumTri(const ManifoldAdapter* value, NativeError* error) noexcept
                 {
                     return Guard<std::size_t>(error, 0, [&]() { return value->Value->NumTri(); });
                 }

                 extern "C" void Manifold_GetMeshCounts(
                     const ManifoldAdapter* value,
                     std::size_t* vertexCount,
                     std::size_t* indexCount,
                     NativeError* error) noexcept
                 {
                     Guard<int>(error, 0, [&]()
                     {
                         const auto mesh = value->Value->GetMeshGL64();
                         *vertexCount = mesh.vertProperties.size();
                         *indexCount = mesh.triVerts.size();
                         return 1;
                     });
                 }

                 extern "C" void Manifold_CopyMesh(
                     const ManifoldAdapter* value,
                     double* vertices,
                     std::size_t vertexCount,
                     std::uint64_t* indices,
                     std::size_t indexCount,
                     NativeError* error) noexcept
                 {
                     Guard<int>(error, 0, [&]()
                     {
                         const auto mesh = value->Value->GetMeshGL64();
                         if (mesh.vertProperties.size() != vertexCount || mesh.triVerts.size() != indexCount)
                             throw std::invalid_argument("Mesh output length changed between count and copy.");
                         if (vertexCount != 0) std::copy(mesh.vertProperties.begin(), mesh.vertProperties.end(), vertices);
                         if (indexCount != 0) std::copy(mesh.triVerts.begin(), mesh.triVerts.end(), indices);
                         return 1;
                     });
                 }

                 extern "C" __declspec(dllexport) const std::uintptr_t* NativeApi_GetFunctionTable() noexcept
                 {
                     static const std::uintptr_t Functions[] =
                     {
                 {{functionPointers}}
                     };
                     return Functions;
                 }
                 """;
    }

    internal static string RenderCMake(ManifoldProfile profile)
    {
        return $$"""
                 cmake_minimum_required(VERSION 3.28)
                 project(TedToolkitCppBindingsManifold LANGUAGES CXX)

                 file(WRITE "${CMAKE_BINARY_DIR}/compiler-identity.txt"
                     "${CMAKE_CXX_COMPILER_ID}|${CMAKE_CXX_COMPILER_VERSION}|${CMAKE_CXX_COMPILER}")

                 find_package(manifold CONFIG REQUIRED)

                 add_library({{profile.NativeLibraryBaseName}} SHARED ManifoldProfileAdapter.cpp)
                 target_compile_features({{profile.NativeLibraryBaseName}} PRIVATE cxx_std_20)
                 target_compile_options({{profile.NativeLibraryBaseName}} PRIVATE /MP1)
                 target_link_libraries({{profile.NativeLibraryBaseName}} PRIVATE manifold::manifold)
                 """;
    }
}
