// -----------------------------------------------------------------------
// <copyright file="ManifoldSemanticProfile.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using TedToolkit.CppBindings.Generator.Semantics;

namespace TedToolkit.CppBindings.Manifold.Generator;

/// <summary>Supplies the finite Manifold policies consumed by Shared.</summary>
internal static class ManifoldSemanticProfile
{
    internal const string ManagedSourceStem = "managed-source-stem";

    internal const string NativeSourceStem = "native-source-stem";

    internal static BindingSemanticEngine Create()
    {
        return new(
            [new TypeRule(),],
            new LayoutPolicy(),
            new TemplatePolicy(),
            [new SourceStemEmitter(ManagedSourceStem), new SourceStemEmitter(NativeSourceStem),]);
    }

    internal static BindingEmissionProfile CreateEmissionProfile()
    {
        return new()
        {
            CSharpNamespace = "TedToolkit.CppBindings.Manifold",
            ManagedNativeErrorProjection = "global::TedToolkit.CppBindings.Manifold.NativeErrorProjection",
            NativeErrorClearExport = "Manifold_NativeError_Clear",
            NativePreamble = "// <auto-generated />\n",
            NativeErrorPreamble = "",
            NativeErrorSetter = "SetError",
        };
    }

    private sealed class TypeRule : IBindingTypeRule
    {
        public bool TryResolve(CppTypeDescriptor type, out BindingTypeProjection? projection)
        {
            projection = new(type.NativeName, type.NativeName);
            return true;
        }
    }

    private sealed class LayoutPolicy : IBindingLayoutPolicy
    {
        public BindingAdmission Admit(BindingLayoutDescriptor layout)
        {
            return BindingAdmission.Admitted;
        }
    }

    private sealed class TemplatePolicy : IBindingTemplatePolicy
    {
        public BindingAdmission Admit(BindingTemplateDescriptor template)
        {
            return template.IsClosed
                ? BindingAdmission.Admitted
                : BindingAdmission.Reject("The Manifold profile admits only closed templates.");
        }
    }

    private sealed class SourceStemEmitter(string name) : IBindingEmitterPrimitive
    {
        public string Name
        {
            get
            {
                return name;
            }
        }

        public string Emit(string value)
        {
            return value.Replace("::", "_", StringComparison.Ordinal);
        }
    }
}