on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-build-project:
    uses: TedToolkit/TedToolkit/.github/workflows/build.yml@b9152e16ef9e227a2540b86b90af5391374cfd90
    secrets: inherit
